questone2/cfg/questone2-modules.conf etc/modules-load.d
questone2/cfg/questone2-modprobe.conf etc/modprobe.d
questone2/systemd/platform-modules-questone2.service lib/systemd/system
questone2/cfg/pid_config_questone2.ini usr/local/etc
questone2/modules/sonic_platform-1.0-py3-none-any.whl usr/share/sonic/device/x86_64-cel_questone_2-r0
services/platform_api/platform_api_mgnt.sh usr/local/bin
services/platform_api/ps_mem.py usr/local/bin
