depmod -a

# Enable bmc vlan_ip service
systemctl enable bmc_vlan.service

systemctl enable platform-modules-questone2f.service
systemctl start platform-modules-questone2f.service

# Enable platform-sync_bmc-timer
# systemctl enable sync_bmc.timer
# systemctl start sync_bmc.timer

# Enable heartbeat timer
systemctl enable bmc_wdt.service
systemctl start bmc_wdt.service

# Enable bmc console logging service
systemctl enable bmc-console-log.service
systemctl start bmc-console-log.service
