#!/bin/bash

### BEGIN INIT INFO
# Provides:          setup-board
# Required-Start:    $portmap
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Setup questone2 board.
### END INIT INFO


case "$1" in
start)
        echo -n "Setting up board... "

        # Loads kernel modules
        modprobe questone2_baseboard_cpld
        modprobe questone2_switchboard
        modprobe mc24lc64t
        modprobe optoe
        modprobe sff_8436_eeprom

        # Add driver to support TLV - EEPROM
        echo 24lc64t 0x56 > /sys/bus/i2c/devices/i2c-0/new_device

        echo "done."
        ;;

stop)
        echo "done."
        ;;

force-reload|restart)
        echo "Not supported"
        ;;

*)
        echo "Usage: /etc/init.d/platform-modules-questone2 {start|stop}"
        exit 1
        ;;
esac

exit 0
