# Asterfusion barefoot platform


ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE_VERSION = 1.0
ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE_VERSION = 1.0
ASTERFUSION_CX564P_T_PLATFORM_MODULE_VERSION = 1.0
ASTERFUSION_CX532P_T_PLATFORM_MODULE_VERSION = 1.0

export ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX532P_T_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX564P_T_PLATFORM_MODULE_VERSION

ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE = sonic-platform-asterfusion-cx308p-48y-t_$(ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-asterfusion
$(ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx308p_48y_t-r0
SONIC_DPKG_DEBS += $(ASTERFUSION_CX308P_48Y_T_PLATFORM_MODULE)

ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE = sonic-platform-asterfusion-cx312p-48y-t_$(ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-asterfusion
$(ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx312p_48y_t-r0
SONIC_DPKG_DEBS += $(ASTERFUSION_CX312P_48Y_T_PLATFORM_MODULE)

ASTERFUSION_CX532P_T_PLATFORM_MODULE = sonic-platform-asterfusion-cx532p-t_$(ASTERFUSION_CX532P_T_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX532P_T_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-asterfusion
$(ASTERFUSION_CX532P_T_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX532P_T_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx532p_t-r0
SONIC_DPKG_DEBS += $(ASTERFUSION_CX532P_T_PLATFORM_MODULE)

ASTERFUSION_CX564P_T_PLATFORM_MODULE = sonic-platform-asterfusion-cx564p-t_$(ASTERFUSION_CX564P_T_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX564P_T_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-asterfusion
$(ASTERFUSION_CX564P_T_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX564P_T_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx564p_t-r0
SONIC_DPKG_DEBS += $(ASTERFUSION_CX564P_T_PLATFORM_MODULE)
