#! /usr/bin/env python
# coding:utf-8

try:
    import os
    from fan_ctrl_pkg.fan_utility import FanUtility
    from fan_ctrl_pkg import fan_ctrl_parser as arg
    from fan_ctrl_pkg import __main__
except ImportError as e:
    raise ImportError("%s - required module not found" % str(e))


if __name__ == '__main__':
    zone_conf, temp_conf, log_file, debug_mode, simulate_mode = arg.fan_ctrl_parser(os.path.dirname(os.path.abspath(__file__)))
    FanUtility.platform_init(os.path.dirname(os.path.abspath(__file__)), zone_conf, temp_conf, simulate_mode)
    __main__.main(zone_conf, temp_conf, log_file, debug_mode, simulate_mode)
