
# Copyright (C) 2009 Realtek Semiconductor Corp.
#
# Makefile for SDK Linux Stacking Module
#

MODULE_SRC_PATH     := $(ROOT_PATH)/module/example/src

EXAMPLE_OBJ := \
	$(MODULE_SRC_PATH)/test_phyApi.o
