@startuml

title Modules/Files Relationships

package bf_switch_sysfs{
  class bf_switch_sysfs {
    -kobject* switch_kobj;
    +kobject* bf_get_switch_kobj()
    +kobject* create_sysfs_dir_and_attr()
    +void remove_sysfs_dir_and_attr()
    -int bf_switch_sysfs_init()
    -void bf_switch_sysfs_exit()
  }
}

package bf_fan{
  class bf_fan_driver {
    +bf_newport_fan_data data;
    +int bf_fan_init()
    +void bf_fan_exit()
    -int fan_init()
    -void fan_exit()
    -int motor_init()
    -void motr_exit()
    -int bf_fan_create_root_attr()
    -void bf_fan_remove_root_attr()
    -int bf_fan_create_symlink()
    -void bf_fan_remove_symlink()
    -int bf_motor_create_symlink()
    -void bf_motor_remove_symlink()
  }

  class bf_fan_api{
    +ssize_t root_show()
    +ssize_t root_store()
    +ssize_t fan_show()
    +ssize_t fan_store()
    +ssize_t motor_show()
    +ssize_t motor_store()
    +int init_ipmi_data()
    +void ipmi_msg_handler()
    +int update_fan_data()
  }
}

bf_fan_driver --> bf_switch_sysfs : Use >
bf_fan_driver --> bf_fan_api : Use >

@enduml