# MDIO IPC client library

MDIO_IPC_CLIENT_LIB_VERSION = 1.1

export MDIO_IPC_CLIENT_LIB_VERSION

MDIO_IPC_CLIENT_LIBRARY = lib_mdio_ipc_client_$(MDIO_IPC_CLIENT_LIB_VERSION)_amd64.deb
MDIO_IPC_CLIENT_LIBRARY_DBG = lib_mdio_ipc_client-dbg_$(MDIO_IPC_CLIENT_LIB_VERSION)_amd64.deb

$(MDIO_IPC_CLIENT_LIBRARY)_SRC_PATH = platform/components/mdio-ipc-client
SONIC_DPKG_DEBS += $(MDIO_IPC_CLIENT_LIBRARY)
$(eval $(call add_derived_package,$(MDIO_IPC_CLIENT_LIBRARY),$(MDIO_IPC_CLIENT_LIBRARY_DBG)))

$(MDIO_IPC_CLIENT_LIBRARY)_DEPENDS += $(BRCM_SAI_DEV)

