#!/bin/bash

i2c_flag=0
sudo ipmitool raw 0x30 0x85 1
for i in $(seq 0 9)
do
    sleep 0.5
    if [ "$(sudo i2cdetect -y 0 | sed 's/^..//' | grep 71)" == "" ];then
        i2c_flag=1
        break
    fi
done
if [ $i2c_flag -eq 0 ];then
    sudo ipmitool raw 0x06 0x02
fi

/usr/local/bin/sonic-fanthrml-monitor &
/usr/local/bin/sonic-led-monitor &
/usr/local/bin/sonic-qsfp-monitor &
/usr/local/bin/sonic-psu-monitor &
exit 0

