#!/usr/bin/python
import subprocess

def main():
    # reboot the system
    subprocess.run(['modprobe', 'i2c-dev'])
    subprocess.run(['i2cset', '-y', '0', '0x36', '0x23', '0x0'])
    subprocess.run(['sleep', '1'])
    subprocess.run(['i2cset', '-y', '0', '0x36', '0x23', '0x3'])

if __name__ == "__main__":
    main()
