#!/bin/bash

if [ "$1" == "all" ]; then
    if [ -r /usr/local/bin/cx_sensors.py ]; then
        sudo python /usr/local/bin/cx_sensors.py show fans
        sudo python /usr/local/bin/cx_sensors.py show powers
        docker exec -i pmon sensors
        sudo python /usr/local/bin/cx_sensors.py show temps
        sudo python /usr/local/bin/cx_sensors.py show voltages
    fi
elif [ "$1" == "fans" ]; then
    sudo python /usr/local/bin/cx_sensors.py show fans
elif [ "$1" == "powers" ]; then
    sudo python /usr/local/bin/cx_sensors.py show powers
elif [ "$1" == "temps" ]; then
    docker exec -i pmon sensors
    sudo python /usr/local/bin/cx_sensors.py show temps
elif [ "$1" == "voltages" ]; then
    sudo python /usr/local/bin/cx_sensors.py show voltages
else
    echo "show environment [OPTIONS]"
    echo "OPTIONS:"
    echo "  all       Show system environment status"
    echo "  fans      Show system fans status"
    echo "  powers    Show system PSU powers"
    echo "  temps     Show system temps"
    echo "  voltages  Show system voltages"
fi
