subdir-m := driver
obj-m := pddf_cpld_module.o
#GCOV_PROFILE := y

#$(info  ===========$(M)=========)
CFLAGS_$(obj-m):= -I$(M)/modules/include

#all:
	#$(MAKE) -C /projects/slxos_dev/fk410167/18.2.01X/slxos_main/build/swbd4000/linux_4_9/  M=$(PWD) modules ;

#clean:
	#$(MAKE) -C /projects/slxos_dev/fk410167/18.2.01X/slxos_main/build/swbd4000/linux_4_9/  M=$(PWD) clean ;

