#!/bin/bash

# read SONiC immutable variables
[ -f /etc/sonic/sonic-environment ] && . /etc/sonic/sonic-environment

PLATFORM=${PLATFORM:-`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`}

# Parse the device specific asic conf file, if it exists
ASIC_CONF=/usr/share/sonic/device/$PLATFORM/asic.conf
[ -f $ASIC_CONF ] && . $ASIC_CONF

if [[ ($NUM_ASIC -gt 1) ]]; then
    asic=0
    while [ $asic -lt $NUM_ASIC ]
    do
        echo -e "BGP"$asic" : \c"
        docker exec -i bgp$asic /usr/bin/$1
        asic=$[$asic+1]
    done
else
    echo -e "BGP : \c"
    docker exec -i bgp /usr/bin/$1
fi
