# docker image for physyncd


DOCKER_PHYSYNCD_BASE_STEM = docker-physyncd-$(DOCKER_PHYSYNCD_PLATFORM_CODE)
DOCKER_PHYSYNCD_BASE = $(DOCKER_PHYSYNCD_BASE_STEM).gz
DOCKER_PHYSYNCD_BASE_DBG = $(DOCKER_PHYSYNCD_BASE_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_PHYSYNCD_BASE)_PATH = $(PLATFORM_PATH)/docker-physyncd-$(DOCKER_PHYSYNCD_PLATFORM_CODE)

$(DOCKER_PHYSYNCD_BASE)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

$(DOCKER_PHYSYNCD_BASE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_STRETCH)

$(DOCKER_PHYSYNCD_BASE)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_STRETCH)_DBG_DEPENDS)

$(DOCKER_PHYSYNCD_BASE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_STRETCH)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_PHYSYNCD_BASE)
SONIC_STRETCH_DOCKERS += $(DOCKER_PHYSYNCD_BASE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_PHYSYNCD_BASE)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_PHYSYNCD_BASE_DBG)
SONIC_STRETCH_DBG_DOCKERS += $(DOCKER_PHYSYNCD_BASE_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_PHYSYNCD_BASE_DBG)

$(DOCKER_PHYSYNCD_BASE)_CONTAINER_NAME = physyncd
$(DOCKER_PHYSYNCD_BASE)_RUN_OPT += --net=host --privileged -t
$(DOCKER_PHYSYNCD_BASE)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_PHYSYNCD_BASE)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro

