#!/usr/bin/env python2

"""
    healthd
    System health monitor daemon for SONiC
"""

import signal
import threading
from sonic_daemon_base.daemon_base import Logger
from sonic_daemon_base.daemon_base import DaemonBase
from swsssdk import SonicV2Connector
from health_checker.manager import HealthCheckerManager

SYSLOG_IDENTIFIER = 'healthd'
logger = Logger(SYSLOG_IDENTIFIER)


class HealthDaemon(DaemonBase):
    SYSTEM_HEALTH_TABLE_NAME = 'SYSTEM_HEALTH_INFO'

    def __init__(self):
        """
        Constructor of HealthDaemon
        """
        DaemonBase.__init__(self)
        self._db = SonicV2Connector(host="127.0.0.1")
        self._db.connect(self._db.STATE_DB)
        self.stop_event = threading.Event()

    def deinit(self):
        self._clear_system_health_table()

    def _clear_system_health_table(self):
        self._db.delete_all_by_pattern(self._db.STATE_DB, HealthDaemon.SYSTEM_HEALTH_TABLE_NAME)

    # Signal handler
    def signal_handler(self, sig, frame):
        """
        Signal handler
        :param sig: Signal number
        :param frame: not used
        :return:
        """
        if sig == signal.SIGHUP:
            logger.log_info("Caught SIGHUP - ignoring...")
        elif sig == signal.SIGINT:
            logger.log_info("Caught SIGINT - exiting...")
            self.stop_event.set()
        elif sig == signal.SIGTERM:
            logger.log_info("Caught SIGTERM - exiting...")
            self.stop_event.set()
        else:
            logger.log_warning("Caught unhandled signal '" + sig + "'")

    def run(self):
        logger.log_info("Starting up...")

        import sonic_platform.platform
        chassis = sonic_platform.platform.Platform().get_chassis()
        manager = HealthCheckerManager()
        while 1:
            state, stat = manager.check()
            if state == HealthCheckerManager.STATE_RUNNING:
                self._process_stat(chassis, manager.config, stat)
            else:
                self._set_system_led(chassis, manager.config, 'booting')

            if self.stop_event.wait(manager.config.interval):
                break

        self.deinit()

    def _process_stat(self, chassis, config, stat):
        from health_checker.health_checker import HealthChecker
        self._clear_system_health_table()
        status = True
        for category, info in stat.items():
            for obj_name, obj_data in info.items():
                if obj_data[HealthChecker.INFO_FIELD_OBJECT_STATUS] == HealthChecker.STATUS_NOT_OK:
                    status = False
                    self._db.set(self._db.STATE_DB, HealthDaemon.SYSTEM_HEALTH_TABLE_NAME, obj_name,
                                 obj_data[HealthChecker.INFO_FIELD_OBJECT_MSG])

        summary = 'OK' if status else 'Not OK'
        self._db.set(self._db.STATE_DB, HealthDaemon.SYSTEM_HEALTH_TABLE_NAME, 'summary', summary)
        led_status = 'normal' if status else 'fault'
        self._set_system_led(chassis, config, led_status)

    def _set_system_led(self, chassis, config, status):
        try:
            chassis.set_status_led(config.get_led_color(status))
        except NotImplementedError:
            logger.log_info('chassis.set_status_led is not implemented')
        except Exception as e:
            logger.log_error('Failed to set system led due to - {}'.format(repr(e)))


#
# Main =========================================================================
#
def main():
    thermal_control = HealthDaemon()
    thermal_control.run()


if __name__ == '__main__':
    main()
