#!/bin/bash

### BEGIN INIT INFO
# Provides:          setup-board-i2c
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Setup ly1200-32x board.
### END INIT INFO

I2C_BUS_RM_ALL=0
I2C_I801_RM_PRINT=0
I2C_ISMT_RM_PRINT=0
I2C_I801_INS_PRINT=0
I2C_ISMT_INS_PRINT=0
I2C_I801_RM_RETRY=0
I2C_ISMT_RM_RETRY=0
I2C_I801_INS_RETRY=0
I2C_ISMT_INS_RETRY=0
RETRY=3

# process name/id
DAEMON_NAME=`basename $0`
DAEMON_PID="$$"

# default log file
DEF_LOG_FILE="/var/log/syslog"

#/*
#* FEATURE:
#*   log_msg
#* PURPOSE:
#*   log message
#* PARAMETERS:
#*   msg                  (IN) message
#* RETURNS:
#*
#*/
function log_msg() {
  local msg=$1

  echo -e "`date +"%b %_d %T"` `hostname` $DAEMON_NAME[$DAEMON_PID]: ${msg}" >> ${DEF_LOG_FILE}
}


# Load kernel modules
load_modules () {
        modprobe i2c_i801
        modprobe i2c_ismt

        if [ `lsmod | grep -c "at24 "` -eq 0 ]; then
                modprobe at24
        fi
        if [ `lsmod | grep -c "i2c_mux "` -eq 0 ]; then
                modprobe i2c_mux
        fi
        if [ `lsmod | grep -c "i2c_mux_pca954x "` -eq 0 ]; then
                modprobe i2c_mux_pca954x
        fi
        if [ `lsmod | grep -c "lm75 "` -eq 0 ]; then
                modprobe lm75
        fi
        if [ `lsmod | grep -c "max31790 "` -eq 0 ]; then
                modprobe max31790
        fi
        if [ `lsmod | grep -c "sff_8436_eeprom "` -eq 0 ]; then
                modprobe sff_8436_eeprom
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_fse000 "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_fse000
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_system_cpld "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_system_cpld
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_master_cpld "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_master_cpld
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_slave_cpld "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_slave_cpld
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_cb_i2c "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_cb_i2c
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_sb_i2c "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_sb_i2c
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_pb_i2c "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_pb_i2c
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_fb_i2c "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_fb_i2c
        fi
        if [ `lsmod | grep -c "mitac_ly1200_32x_fb_module_i2c "` -eq 0 ]; then
                modprobe mitac_ly1200_32x_fb_module_i2c
        fi
}

# Load i2c_dev modules
load_i2c_dev_modules () {
        if [ `lsmod | grep -c "i2c_dev "` -eq 0 ]; then
                modprobe i2c_dev
        fi
}

# Load nvmem_core modules
load_nvmem_core_modules () {
        if [ `lsmod | grep -c "nvmem_core "` -eq 0 ]; then
                modprobe nvmem_core
        fi
}

case "$1" in
start)
    echo -n "Loading modules for board... "
    load_i2c_dev_modules
    load_nvmem_core_modules
    load_modules
    echo "done."
    ;;

stop)
    echo -n "cleaning... "
    echo "done."

    ;;

force-reload|restart)
    echo "Not supported"
    ;;

*)
    echo "Usage: /etc/init.d/i2c_init {start|stop}"
    exit 1
    ;;
esac

exit 0
