obj-m := dni_agv848v1_psu.o dni_emc2305.o delta_agv848v1_platform.o delta_agv848v1_sfp.o delta_agv848v1_swpld.o
#obj-m := dni_agv848v1_psu.o dni_emc2305.o delta_agv848v1_platform.o delta_agv848v1_cpupld.o dni_emc2302.o delta_agv848v1_swpld.o delta_agv848v1_sfp.o
