// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rebootbackend/container_stop.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rebootbackend_2fcontainer_5fstop_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rebootbackend_2fcontainer_5fstop_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rebootbackend_2fcontainer_5fstop_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rebootbackend_2fcontainer_5fstop_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto;
class ContainerStatus;
class ContainerStatusDefaultTypeInternal;
extern ContainerStatusDefaultTypeInternal _ContainerStatus_default_instance_;
class StopContainersRequest;
class StopContainersRequestDefaultTypeInternal;
extern StopContainersRequestDefaultTypeInternal _StopContainersRequest_default_instance_;
class StopContainersResponse;
class StopContainersResponseDefaultTypeInternal;
extern StopContainersResponseDefaultTypeInternal _StopContainersResponse_default_instance_;
class StopContainersResponse_ContainerStatusEntry_DoNotUse;
class StopContainersResponse_ContainerStatusEntry_DoNotUseDefaultTypeInternal;
extern StopContainersResponse_ContainerStatusEntry_DoNotUseDefaultTypeInternal _StopContainersResponse_ContainerStatusEntry_DoNotUse_default_instance_;
class StopContainersStatusRequest;
class StopContainersStatusRequestDefaultTypeInternal;
extern StopContainersStatusRequestDefaultTypeInternal _StopContainersStatusRequest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ContainerStatus* Arena::CreateMaybeMessage<::ContainerStatus>(Arena*);
template<> ::StopContainersRequest* Arena::CreateMaybeMessage<::StopContainersRequest>(Arena*);
template<> ::StopContainersResponse* Arena::CreateMaybeMessage<::StopContainersResponse>(Arena*);
template<> ::StopContainersResponse_ContainerStatusEntry_DoNotUse* Arena::CreateMaybeMessage<::StopContainersResponse_ContainerStatusEntry_DoNotUse>(Arena*);
template<> ::StopContainersStatusRequest* Arena::CreateMaybeMessage<::StopContainersStatusRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum ShutdownStatus : int {
  NOT_STARTED = 0,
  WAITING_FOR_NICE_SHUTDOWN = 1,
  WAITING_FOR_FORCE_SHUTDOWN = 2,
  DONE = 3,
  ERROR = 4,
  ShutdownStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ShutdownStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ShutdownStatus_IsValid(int value);
constexpr ShutdownStatus ShutdownStatus_MIN = NOT_STARTED;
constexpr ShutdownStatus ShutdownStatus_MAX = ERROR;
constexpr int ShutdownStatus_ARRAYSIZE = ShutdownStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ShutdownStatus_descriptor();
template<typename T>
inline const std::string& ShutdownStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ShutdownStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ShutdownStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ShutdownStatus_descriptor(), enum_t_value);
}
inline bool ShutdownStatus_Parse(
    const std::string& name, ShutdownStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ShutdownStatus>(
    ShutdownStatus_descriptor(), name, value);
}
// ===================================================================

class StopContainersRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:StopContainersRequest) */ {
 public:
  inline StopContainersRequest() : StopContainersRequest(nullptr) {};
  virtual ~StopContainersRequest();

  StopContainersRequest(const StopContainersRequest& from);
  StopContainersRequest(StopContainersRequest&& from) noexcept
    : StopContainersRequest() {
    *this = ::std::move(from);
  }

  inline StopContainersRequest& operator=(const StopContainersRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopContainersRequest& operator=(StopContainersRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StopContainersRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopContainersRequest* internal_default_instance() {
    return reinterpret_cast<const StopContainersRequest*>(
               &_StopContainersRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StopContainersRequest& a, StopContainersRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StopContainersRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopContainersRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StopContainersRequest* New() const final {
    return CreateMaybeMessage<StopContainersRequest>(nullptr);
  }

  StopContainersRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StopContainersRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StopContainersRequest& from);
  void MergeFrom(const StopContainersRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopContainersRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "StopContainersRequest";
  }
  protected:
  explicit StopContainersRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto);
    return ::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContainerNamesFieldNumber = 2,
    kRequestIdFieldNumber = 1,
  };
  // repeated string container_names = 2;
  int container_names_size() const;
  private:
  int _internal_container_names_size() const;
  public:
  void clear_container_names();
  const std::string& container_names(int index) const;
  std::string* mutable_container_names(int index);
  void set_container_names(int index, const std::string& value);
  void set_container_names(int index, std::string&& value);
  void set_container_names(int index, const char* value);
  void set_container_names(int index, const char* value, size_t size);
  std::string* add_container_names();
  void add_container_names(const std::string& value);
  void add_container_names(std::string&& value);
  void add_container_names(const char* value);
  void add_container_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& container_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_container_names();
  private:
  const std::string& _internal_container_names(int index) const;
  std::string* _internal_add_container_names();
  public:

  // string request_id = 1;
  bool has_request_id() const;
  private:
  bool _internal_has_request_id() const;
  public:
  void clear_request_id();
  const std::string& request_id() const;
  void set_request_id(const std::string& value);
  void set_request_id(std::string&& value);
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  std::string* mutable_request_id();
  std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_request_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_request_id(
      std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // @@protoc_insertion_point(class_scope:StopContainersRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> container_names_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
  friend struct ::TableStruct_rebootbackend_2fcontainer_5fstop_2eproto;
};
// -------------------------------------------------------------------

class ContainerStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ContainerStatus) */ {
 public:
  inline ContainerStatus() : ContainerStatus(nullptr) {};
  virtual ~ContainerStatus();

  ContainerStatus(const ContainerStatus& from);
  ContainerStatus(ContainerStatus&& from) noexcept
    : ContainerStatus() {
    *this = ::std::move(from);
  }

  inline ContainerStatus& operator=(const ContainerStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ContainerStatus& operator=(ContainerStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ContainerStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContainerStatus* internal_default_instance() {
    return reinterpret_cast<const ContainerStatus*>(
               &_ContainerStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ContainerStatus& a, ContainerStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(ContainerStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ContainerStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ContainerStatus* New() const final {
    return CreateMaybeMessage<ContainerStatus>(nullptr);
  }

  ContainerStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ContainerStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ContainerStatus& from);
  void MergeFrom(const ContainerStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContainerStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ContainerStatus";
  }
  protected:
  explicit ContainerStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto);
    return ::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string error_message = 2;
  bool has_error_message() const;
  private:
  bool _internal_has_error_message() const;
  public:
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // .ShutdownStatus status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::ShutdownStatus status() const;
  void set_status(::ShutdownStatus value);
  private:
  ::ShutdownStatus _internal_status() const;
  void _internal_set_status(::ShutdownStatus value);
  public:

  // @@protoc_insertion_point(class_scope:ContainerStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  int status_;
  friend struct ::TableStruct_rebootbackend_2fcontainer_5fstop_2eproto;
};
// -------------------------------------------------------------------

class StopContainersStatusRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:StopContainersStatusRequest) */ {
 public:
  inline StopContainersStatusRequest() : StopContainersStatusRequest(nullptr) {};
  virtual ~StopContainersStatusRequest();

  StopContainersStatusRequest(const StopContainersStatusRequest& from);
  StopContainersStatusRequest(StopContainersStatusRequest&& from) noexcept
    : StopContainersStatusRequest() {
    *this = ::std::move(from);
  }

  inline StopContainersStatusRequest& operator=(const StopContainersStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopContainersStatusRequest& operator=(StopContainersStatusRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StopContainersStatusRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopContainersStatusRequest* internal_default_instance() {
    return reinterpret_cast<const StopContainersStatusRequest*>(
               &_StopContainersStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StopContainersStatusRequest& a, StopContainersStatusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StopContainersStatusRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopContainersStatusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StopContainersStatusRequest* New() const final {
    return CreateMaybeMessage<StopContainersStatusRequest>(nullptr);
  }

  StopContainersStatusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StopContainersStatusRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StopContainersStatusRequest& from);
  void MergeFrom(const StopContainersStatusRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopContainersStatusRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "StopContainersStatusRequest";
  }
  protected:
  explicit StopContainersStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto);
    return ::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestIdFieldNumber = 1,
  };
  // string request_id = 1;
  bool has_request_id() const;
  private:
  bool _internal_has_request_id() const;
  public:
  void clear_request_id();
  const std::string& request_id() const;
  void set_request_id(const std::string& value);
  void set_request_id(std::string&& value);
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  std::string* mutable_request_id();
  std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_request_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_request_id(
      std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // @@protoc_insertion_point(class_scope:StopContainersStatusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
  friend struct ::TableStruct_rebootbackend_2fcontainer_5fstop_2eproto;
};
// -------------------------------------------------------------------

class StopContainersResponse_ContainerStatusEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<StopContainersResponse_ContainerStatusEntry_DoNotUse, 
    std::string, ::ContainerStatus,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<StopContainersResponse_ContainerStatusEntry_DoNotUse, 
    std::string, ::ContainerStatus,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  StopContainersResponse_ContainerStatusEntry_DoNotUse();
  StopContainersResponse_ContainerStatusEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const StopContainersResponse_ContainerStatusEntry_DoNotUse& other);
  static const StopContainersResponse_ContainerStatusEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const StopContainersResponse_ContainerStatusEntry_DoNotUse*>(&_StopContainersResponse_ContainerStatusEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "StopContainersResponse.ContainerStatusEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto);
    return ::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto.file_level_metadata[3];
  }

  public:
};

// -------------------------------------------------------------------

class StopContainersResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:StopContainersResponse) */ {
 public:
  inline StopContainersResponse() : StopContainersResponse(nullptr) {};
  virtual ~StopContainersResponse();

  StopContainersResponse(const StopContainersResponse& from);
  StopContainersResponse(StopContainersResponse&& from) noexcept
    : StopContainersResponse() {
    *this = ::std::move(from);
  }

  inline StopContainersResponse& operator=(const StopContainersResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopContainersResponse& operator=(StopContainersResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StopContainersResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopContainersResponse* internal_default_instance() {
    return reinterpret_cast<const StopContainersResponse*>(
               &_StopContainersResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StopContainersResponse& a, StopContainersResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StopContainersResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopContainersResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StopContainersResponse* New() const final {
    return CreateMaybeMessage<StopContainersResponse>(nullptr);
  }

  StopContainersResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StopContainersResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StopContainersResponse& from);
  void MergeFrom(const StopContainersResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopContainersResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "StopContainersResponse";
  }
  protected:
  explicit StopContainersResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto);
    return ::descriptor_table_rebootbackend_2fcontainer_5fstop_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kContainerStatusFieldNumber = 3,
    kErrorMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // map<string, .ContainerStatus> container_status = 3;
  int container_status_size() const;
  private:
  int _internal_container_status_size() const;
  public:
  void clear_container_status();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >&
      _internal_container_status() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >*
      _internal_mutable_container_status();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >&
      container_status() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >*
      mutable_container_status();

  // string error_message = 2;
  bool has_error_message() const;
  private:
  bool _internal_has_error_message() const;
  public:
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // .ShutdownStatus status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::ShutdownStatus status() const;
  void set_status(::ShutdownStatus value);
  private:
  ::ShutdownStatus _internal_status() const;
  void _internal_set_status(::ShutdownStatus value);
  public:

  // @@protoc_insertion_point(class_scope:StopContainersResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      StopContainersResponse_ContainerStatusEntry_DoNotUse,
      std::string, ::ContainerStatus,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > container_status_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  int status_;
  friend struct ::TableStruct_rebootbackend_2fcontainer_5fstop_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StopContainersRequest

// string request_id = 1;
inline bool StopContainersRequest::_internal_has_request_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StopContainersRequest::has_request_id() const {
  return _internal_has_request_id();
}
inline void StopContainersRequest::clear_request_id() {
  request_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StopContainersRequest::request_id() const {
  // @@protoc_insertion_point(field_get:StopContainersRequest.request_id)
  return _internal_request_id();
}
inline void StopContainersRequest::set_request_id(const std::string& value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:StopContainersRequest.request_id)
}
inline std::string* StopContainersRequest::mutable_request_id() {
  // @@protoc_insertion_point(field_mutable:StopContainersRequest.request_id)
  return _internal_mutable_request_id();
}
inline const std::string& StopContainersRequest::_internal_request_id() const {
  return request_id_.Get();
}
inline void StopContainersRequest::_internal_set_request_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StopContainersRequest::set_request_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:StopContainersRequest.request_id)
}
inline void StopContainersRequest::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:StopContainersRequest.request_id)
}
inline void StopContainersRequest::set_request_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:StopContainersRequest.request_id)
}
inline std::string* StopContainersRequest::_internal_mutable_request_id() {
  _has_bits_[0] |= 0x00000001u;
  return request_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StopContainersRequest::release_request_id() {
  // @@protoc_insertion_point(field_release:StopContainersRequest.request_id)
  if (!_internal_has_request_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return request_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StopContainersRequest::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  request_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:StopContainersRequest.request_id)
}
inline std::string* StopContainersRequest::unsafe_arena_release_request_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:StopContainersRequest.request_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return request_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StopContainersRequest::unsafe_arena_set_allocated_request_id(
    std::string* request_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (request_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  request_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      request_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:StopContainersRequest.request_id)
}

// repeated string container_names = 2;
inline int StopContainersRequest::_internal_container_names_size() const {
  return container_names_.size();
}
inline int StopContainersRequest::container_names_size() const {
  return _internal_container_names_size();
}
inline void StopContainersRequest::clear_container_names() {
  container_names_.Clear();
}
inline std::string* StopContainersRequest::add_container_names() {
  // @@protoc_insertion_point(field_add_mutable:StopContainersRequest.container_names)
  return _internal_add_container_names();
}
inline const std::string& StopContainersRequest::_internal_container_names(int index) const {
  return container_names_.Get(index);
}
inline const std::string& StopContainersRequest::container_names(int index) const {
  // @@protoc_insertion_point(field_get:StopContainersRequest.container_names)
  return _internal_container_names(index);
}
inline std::string* StopContainersRequest::mutable_container_names(int index) {
  // @@protoc_insertion_point(field_mutable:StopContainersRequest.container_names)
  return container_names_.Mutable(index);
}
inline void StopContainersRequest::set_container_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:StopContainersRequest.container_names)
  container_names_.Mutable(index)->assign(value);
}
inline void StopContainersRequest::set_container_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:StopContainersRequest.container_names)
  container_names_.Mutable(index)->assign(std::move(value));
}
inline void StopContainersRequest::set_container_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  container_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:StopContainersRequest.container_names)
}
inline void StopContainersRequest::set_container_names(int index, const char* value, size_t size) {
  container_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:StopContainersRequest.container_names)
}
inline std::string* StopContainersRequest::_internal_add_container_names() {
  return container_names_.Add();
}
inline void StopContainersRequest::add_container_names(const std::string& value) {
  container_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:StopContainersRequest.container_names)
}
inline void StopContainersRequest::add_container_names(std::string&& value) {
  container_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:StopContainersRequest.container_names)
}
inline void StopContainersRequest::add_container_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  container_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:StopContainersRequest.container_names)
}
inline void StopContainersRequest::add_container_names(const char* value, size_t size) {
  container_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:StopContainersRequest.container_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
StopContainersRequest::container_names() const {
  // @@protoc_insertion_point(field_list:StopContainersRequest.container_names)
  return container_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
StopContainersRequest::mutable_container_names() {
  // @@protoc_insertion_point(field_mutable_list:StopContainersRequest.container_names)
  return &container_names_;
}

// -------------------------------------------------------------------

// ContainerStatus

// .ShutdownStatus status = 1;
inline bool ContainerStatus::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ContainerStatus::has_status() const {
  return _internal_has_status();
}
inline void ContainerStatus::clear_status() {
  status_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::ShutdownStatus ContainerStatus::_internal_status() const {
  return static_cast< ::ShutdownStatus >(status_);
}
inline ::ShutdownStatus ContainerStatus::status() const {
  // @@protoc_insertion_point(field_get:ContainerStatus.status)
  return _internal_status();
}
inline void ContainerStatus::_internal_set_status(::ShutdownStatus value) {
  _has_bits_[0] |= 0x00000002u;
  status_ = value;
}
inline void ContainerStatus::set_status(::ShutdownStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:ContainerStatus.status)
}

// string error_message = 2;
inline bool ContainerStatus::_internal_has_error_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ContainerStatus::has_error_message() const {
  return _internal_has_error_message();
}
inline void ContainerStatus::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ContainerStatus::error_message() const {
  // @@protoc_insertion_point(field_get:ContainerStatus.error_message)
  return _internal_error_message();
}
inline void ContainerStatus::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:ContainerStatus.error_message)
}
inline std::string* ContainerStatus::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:ContainerStatus.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& ContainerStatus::_internal_error_message() const {
  return error_message_.Get();
}
inline void ContainerStatus::_internal_set_error_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ContainerStatus::set_error_message(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ContainerStatus.error_message)
}
inline void ContainerStatus::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ContainerStatus.error_message)
}
inline void ContainerStatus::set_error_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ContainerStatus.error_message)
}
inline std::string* ContainerStatus::_internal_mutable_error_message() {
  _has_bits_[0] |= 0x00000001u;
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ContainerStatus::release_error_message() {
  // @@protoc_insertion_point(field_release:ContainerStatus.error_message)
  if (!_internal_has_error_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return error_message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ContainerStatus::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ContainerStatus.error_message)
}
inline std::string* ContainerStatus::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ContainerStatus.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ContainerStatus::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ContainerStatus.error_message)
}

// -------------------------------------------------------------------

// StopContainersStatusRequest

// string request_id = 1;
inline bool StopContainersStatusRequest::_internal_has_request_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StopContainersStatusRequest::has_request_id() const {
  return _internal_has_request_id();
}
inline void StopContainersStatusRequest::clear_request_id() {
  request_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StopContainersStatusRequest::request_id() const {
  // @@protoc_insertion_point(field_get:StopContainersStatusRequest.request_id)
  return _internal_request_id();
}
inline void StopContainersStatusRequest::set_request_id(const std::string& value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:StopContainersStatusRequest.request_id)
}
inline std::string* StopContainersStatusRequest::mutable_request_id() {
  // @@protoc_insertion_point(field_mutable:StopContainersStatusRequest.request_id)
  return _internal_mutable_request_id();
}
inline const std::string& StopContainersStatusRequest::_internal_request_id() const {
  return request_id_.Get();
}
inline void StopContainersStatusRequest::_internal_set_request_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StopContainersStatusRequest::set_request_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:StopContainersStatusRequest.request_id)
}
inline void StopContainersStatusRequest::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:StopContainersStatusRequest.request_id)
}
inline void StopContainersStatusRequest::set_request_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:StopContainersStatusRequest.request_id)
}
inline std::string* StopContainersStatusRequest::_internal_mutable_request_id() {
  _has_bits_[0] |= 0x00000001u;
  return request_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StopContainersStatusRequest::release_request_id() {
  // @@protoc_insertion_point(field_release:StopContainersStatusRequest.request_id)
  if (!_internal_has_request_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return request_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StopContainersStatusRequest::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  request_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:StopContainersStatusRequest.request_id)
}
inline std::string* StopContainersStatusRequest::unsafe_arena_release_request_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:StopContainersStatusRequest.request_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return request_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StopContainersStatusRequest::unsafe_arena_set_allocated_request_id(
    std::string* request_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (request_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  request_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      request_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:StopContainersStatusRequest.request_id)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// StopContainersResponse

// .ShutdownStatus status = 1;
inline bool StopContainersResponse::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool StopContainersResponse::has_status() const {
  return _internal_has_status();
}
inline void StopContainersResponse::clear_status() {
  status_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::ShutdownStatus StopContainersResponse::_internal_status() const {
  return static_cast< ::ShutdownStatus >(status_);
}
inline ::ShutdownStatus StopContainersResponse::status() const {
  // @@protoc_insertion_point(field_get:StopContainersResponse.status)
  return _internal_status();
}
inline void StopContainersResponse::_internal_set_status(::ShutdownStatus value) {
  _has_bits_[0] |= 0x00000002u;
  status_ = value;
}
inline void StopContainersResponse::set_status(::ShutdownStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:StopContainersResponse.status)
}

// string error_message = 2;
inline bool StopContainersResponse::_internal_has_error_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StopContainersResponse::has_error_message() const {
  return _internal_has_error_message();
}
inline void StopContainersResponse::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StopContainersResponse::error_message() const {
  // @@protoc_insertion_point(field_get:StopContainersResponse.error_message)
  return _internal_error_message();
}
inline void StopContainersResponse::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:StopContainersResponse.error_message)
}
inline std::string* StopContainersResponse::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:StopContainersResponse.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& StopContainersResponse::_internal_error_message() const {
  return error_message_.Get();
}
inline void StopContainersResponse::_internal_set_error_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StopContainersResponse::set_error_message(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:StopContainersResponse.error_message)
}
inline void StopContainersResponse::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:StopContainersResponse.error_message)
}
inline void StopContainersResponse::set_error_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:StopContainersResponse.error_message)
}
inline std::string* StopContainersResponse::_internal_mutable_error_message() {
  _has_bits_[0] |= 0x00000001u;
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StopContainersResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:StopContainersResponse.error_message)
  if (!_internal_has_error_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return error_message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StopContainersResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:StopContainersResponse.error_message)
}
inline std::string* StopContainersResponse::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:StopContainersResponse.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StopContainersResponse::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:StopContainersResponse.error_message)
}

// map<string, .ContainerStatus> container_status = 3;
inline int StopContainersResponse::_internal_container_status_size() const {
  return container_status_.size();
}
inline int StopContainersResponse::container_status_size() const {
  return _internal_container_status_size();
}
inline void StopContainersResponse::clear_container_status() {
  container_status_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >&
StopContainersResponse::_internal_container_status() const {
  return container_status_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >&
StopContainersResponse::container_status() const {
  // @@protoc_insertion_point(field_map:StopContainersResponse.container_status)
  return _internal_container_status();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >*
StopContainersResponse::_internal_mutable_container_status() {
  return container_status_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ContainerStatus >*
StopContainersResponse::mutable_container_status() {
  // @@protoc_insertion_point(field_mutable_map:StopContainersResponse.container_status)
  return _internal_mutable_container_status();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ShutdownStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ShutdownStatus>() {
  return ::ShutdownStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rebootbackend_2fcontainer_5fstop_2eproto
