#! /bin/bash

SYSTEM_ERR=4

mkdir -p /host/tmp
ret=$?

if [ ${ret} -eq 0 ]; then
    touch /host/tmp/.test_disk_readwrite
    ret=$?
fi

if [ ${ret} -eq 0 ]; then
    exit 0
else
    echo "Read-Only system"
    exit $SYSTEM_ERR
fi
