#! /bin/bash

echo "check_system called"
SYSTEM_ERR=4

# touch /var/log/syslog
# ret=$?

# to help simulate
if [ -f /var/log/read_only ]; then
    ret=${SYSTEM_ERR}
else
    ret=0
fi  

echo "ret=${ret}"

if [ ${ret} -eq 0 ]; then
    exit 0
else
    echo "Read-Only system"
    exit $SYSTEM_ERR
fi
