#! /bin/bash

ssd_type=$(show platform ssdhealth | grep "3IE3" | wc -l)
if [ $ssd_type -ne 0 ];then
    smartctl -a /dev/sda > /tmp/smartctl
    if [ -f /tmp/smartctl ];then
	logger -f /tmp/smartctl
    fi
fi

