{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
ARG image_version
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Pass the image_version to container
ENV IMAGE_VERSION=$image_version
RUN apt-get update      && \
    apt-get install -f -y  \
        arping              \
        iproute2            \
        ndisc6              \
        tcpdump             \
        libelf1             \
        libmnl0             \
        bridge-utils        \
        conntrack           \
        ndppd               \
        pciutils            \
        # Needed for installing netifaces Python package
        build-essential     \
        libdbus-1-3        \
        libdaemon0         \
        libjansson4        \
        libpython2.7       \
        # Install redis-tools dependencies
        # TODO: implicitly install dependencies
        libjemalloc2        \
        ebtables           \
        gdb

{% if docker_stp_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_stp_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_stp_debs.split(' ')) }}
{%- endif %}

# Clean up
RUN apt-get clean -y      && \
    apt-get autoclean -y  && \
    apt-get autoremove -y && \
    rm -rf /debs

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["critical_processes", "/etc/supervisor"]

ENTRYPOINT ["/usr/local/bin/supervisord"]
