FROM docker-config-engine

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Update apt's package index files
RUN apt-get update

# Install required packages
RUN apt-get install -y python-pip sensord fancontrol

{% if docker_platform_monitor_debs.strip() %}
# Copy built Debian packages
COPY \
{% for deb in docker_platform_monitor_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
/debs/
{%- endif %}

{% if docker_platform_monitor_whls.strip() %}
# Copy built Python wheels
COPY \
{% for whl in docker_platform_monitor_whls.split(' ') -%}
python-wheels/{{ whl }}{{' '}}
{%- endfor -%}
/python-wheels/
{%- endif %}

# Copy dependencies of sonic-ledd
COPY ["python-wheels/sonic_platform_common-*-py2-*.whl", "python-wheels/swsssdk-*-py2-*.whl", "/python-wheels/"]

# Install all copied .deb packages
RUN dpkg -i /debs/*.deb

# Install all copied .whl packages
RUN pip install /python-wheels/*.whl

# Clean up
RUN apt-get remove -y python-pip
RUN apt-get clean -y
RUN apt-get autoclean -y
RUN apt-get autoremove -y
RUN rm -rf /debs /python-wheels ~/.cache

COPY ["start.sh", "lm-sensors.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

ENTRYPOINT ["/usr/bin/supervisord"]
