# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\x04\x62\x61se\x1a\ngogo.proto\"\n\n\x08\x45mptyMsg\"g\n\tIPAddress\x12*\n\x02\x41\x66\x18\x01 \x01(\x0e\x32\n.base.IPAFB\x12\xf2\xde\x1f\x0emeta:mandatory\x12\x10\n\x06V4Addr\x18\x02 \x01(\x07H\x00\x12\x10\n\x06V6Addr\x18\x03 \x01(\x0cH\x00\x42\n\n\x08v4_or_v6*7\n\x04IPAF\x12\x0e\n\nIP_AF_NONE\x10\x00\x12\x0e\n\nIP_AF_INET\x10\x01\x12\x0f\n\x0bIP_AF_INET6\x10\x02\x42\x06Z\x04\x62\x61seb\x06proto3')

_IPAF = DESCRIPTOR.enum_types_by_name['IPAF']
IPAF = enum_type_wrapper.EnumTypeWrapper(_IPAF)
IP_AF_NONE = 0
IP_AF_INET = 1
IP_AF_INET6 = 2


_EMPTYMSG = DESCRIPTOR.message_types_by_name['EmptyMsg']
_IPADDRESS = DESCRIPTOR.message_types_by_name['IPAddress']
EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.EmptyMsg)
  })
_sym_db.RegisterMessage(EmptyMsg)

IPAddress = _reflection.GeneratedProtocolMessageType('IPAddress', (_message.Message,), {
  'DESCRIPTOR' : _IPADDRESS,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.IPAddress)
  })
_sym_db.RegisterMessage(IPAddress)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004base'
  _IPADDRESS.fields_by_name['Af']._options = None
  _IPADDRESS.fields_by_name['Af']._serialized_options = b'\362\336\037\016meta:mandatory'
  _IPAF._serialized_start=149
  _IPAF._serialized_end=204
  _EMPTYMSG._serialized_start=32
  _EMPTYMSG._serialized_end=42
  _IPADDRESS._serialized_start=44
  _IPADDRESS._serialized_end=147
# @@protoc_insertion_point(module_scope)
