# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import health_pb2 as health__pb2


class HealthSvcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEeprom = channel.unary_unary(
                '/DpuHealthService.HealthSvc/GetEeprom',
                request_serializer=health__pb2.EepromRequest.SerializeToString,
                response_deserializer=health__pb2.EepromResponse.FromString,
                )
        self.GetHealth = channel.unary_unary(
                '/DpuHealthService.HealthSvc/GetHealth',
                request_serializer=health__pb2.StatusRequest.SerializeToString,
                response_deserializer=health__pb2.StatusResponse.FromString,
                )
        self.GetRebootCauses = channel.unary_unary(
                '/DpuHealthService.HealthSvc/GetRebootCauses',
                request_serializer=health__pb2.RebootCauseRequest.SerializeToString,
                response_deserializer=health__pb2.RebootCauseResponse.FromString,
                )


class HealthSvcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEeprom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRebootCauses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthSvcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEeprom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEeprom,
                    request_deserializer=health__pb2.EepromRequest.FromString,
                    response_serializer=health__pb2.EepromResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=health__pb2.StatusRequest.FromString,
                    response_serializer=health__pb2.StatusResponse.SerializeToString,
            ),
            'GetRebootCauses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRebootCauses,
                    request_deserializer=health__pb2.RebootCauseRequest.FromString,
                    response_serializer=health__pb2.RebootCauseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DpuHealthService.HealthSvc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HealthSvc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEeprom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DpuHealthService.HealthSvc/GetEeprom',
            health__pb2.EepromRequest.SerializeToString,
            health__pb2.EepromResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DpuHealthService.HealthSvc/GetHealth',
            health__pb2.StatusRequest.SerializeToString,
            health__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRebootCauses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DpuHealthService.HealthSvc/GetRebootCauses',
            health__pb2.RebootCauseRequest.SerializeToString,
            health__pb2.RebootCauseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
