# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interrupt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gogo_pb2 as gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import types_pb2 as types__pb2
try:
  gogo__pb2 = types__pb2.gogo__pb2
except AttributeError:
  gogo__pb2 = types__pb2.gogo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='interrupt.proto',
  package='pds',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0finterrupt.proto\x12\x03pds\x1a\ngogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0btypes.proto\"\xae\x02\n\tInterrupt\x12.\n\x04Time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x90\xdf\x1f\x01\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12&\n\x08Severity\x18\x03 \x01(\x0e\x32\x14.pds.Interrupt.Level\x12\r\n\x05\x43ount\x18\x04 \x01(\x04\x12\x13\n\x0b\x44\x65scription\x18\x05 \x01(\t\x12\x12\n\nIgnoreOnce\x18\x06 \x01(\x08\x12\x11\n\tIgnoreAll\x18\x07 \x01(\x08\x12\x13\n\x0bZeroToClear\x18\x08 \x01(\x08\"[\n\x05Level\x12\x0e\n\nLEVEL_NONE\x10\x00\x12\x0f\n\x0bLEVEL_FATAL\x10\x01\x12\x10\n\x0cLEVEL_HW_RMA\x10\x02\x12\x0f\n\x0bLEVEL_ERROR\x10\x03\x12\x0e\n\nLEVEL_INFO\x10\x04\"\"\n\x13InterruptGetRequest\x12\x0b\n\x03\x41ll\x18\x01 \x01(\x08\"^\n\x14InterruptGetResponse\x12#\n\tApiStatus\x18\x01 \x01(\x0e\x32\x10.types.ApiStatus\x12!\n\tInterrupt\x18\x02 \x03(\x0b\x32\x0e.pds.Interrupt2T\n\tSystemSvc\x12G\n\x0cInterruptGet\x12\x18.pds.InterruptGetRequest\x1a\x19.pds.InterruptGetResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[gogo__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,types__pb2.DESCRIPTOR,])



_INTERRUPT_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='pds.Interrupt.Level',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEVEL_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_FATAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_HW_RMA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_INFO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=294,
  serialized_end=385,
)
_sym_db.RegisterEnumDescriptor(_INTERRUPT_LEVEL)


_INTERRUPT = _descriptor.Descriptor(
  name='Interrupt',
  full_name='pds.Interrupt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Time', full_name='pds.Interrupt.Time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220\337\037\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='pds.Interrupt.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Severity', full_name='pds.Interrupt.Severity', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Count', full_name='pds.Interrupt.Count', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Description', full_name='pds.Interrupt.Description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IgnoreOnce', full_name='pds.Interrupt.IgnoreOnce', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IgnoreAll', full_name='pds.Interrupt.IgnoreAll', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ZeroToClear', full_name='pds.Interrupt.ZeroToClear', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INTERRUPT_LEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=385,
)


_INTERRUPTGETREQUEST = _descriptor.Descriptor(
  name='InterruptGetRequest',
  full_name='pds.InterruptGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='All', full_name='pds.InterruptGetRequest.All', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=421,
)


_INTERRUPTGETRESPONSE = _descriptor.Descriptor(
  name='InterruptGetResponse',
  full_name='pds.InterruptGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ApiStatus', full_name='pds.InterruptGetResponse.ApiStatus', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Interrupt', full_name='pds.InterruptGetResponse.Interrupt', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=517,
)

_INTERRUPT.fields_by_name['Time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_INTERRUPT.fields_by_name['Severity'].enum_type = _INTERRUPT_LEVEL
_INTERRUPT_LEVEL.containing_type = _INTERRUPT
_INTERRUPTGETRESPONSE.fields_by_name['ApiStatus'].enum_type = types__pb2._APISTATUS
_INTERRUPTGETRESPONSE.fields_by_name['Interrupt'].message_type = _INTERRUPT
DESCRIPTOR.message_types_by_name['Interrupt'] = _INTERRUPT
DESCRIPTOR.message_types_by_name['InterruptGetRequest'] = _INTERRUPTGETREQUEST
DESCRIPTOR.message_types_by_name['InterruptGetResponse'] = _INTERRUPTGETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Interrupt = _reflection.GeneratedProtocolMessageType('Interrupt', (_message.Message,), {
  'DESCRIPTOR' : _INTERRUPT,
  '__module__' : 'interrupt_pb2'
  # @@protoc_insertion_point(class_scope:pds.Interrupt)
  })
_sym_db.RegisterMessage(Interrupt)

InterruptGetRequest = _reflection.GeneratedProtocolMessageType('InterruptGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTERRUPTGETREQUEST,
  '__module__' : 'interrupt_pb2'
  # @@protoc_insertion_point(class_scope:pds.InterruptGetRequest)
  })
_sym_db.RegisterMessage(InterruptGetRequest)

InterruptGetResponse = _reflection.GeneratedProtocolMessageType('InterruptGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTERRUPTGETRESPONSE,
  '__module__' : 'interrupt_pb2'
  # @@protoc_insertion_point(class_scope:pds.InterruptGetResponse)
  })
_sym_db.RegisterMessage(InterruptGetResponse)


_INTERRUPT.fields_by_name['Time']._options = None

_SYSTEMSVC = _descriptor.ServiceDescriptor(
  name='SystemSvc',
  full_name='pds.SystemSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=519,
  serialized_end=603,
  methods=[
  _descriptor.MethodDescriptor(
    name='InterruptGet',
    full_name='pds.SystemSvc.InterruptGet',
    index=0,
    containing_service=None,
    input_type=_INTERRUPTGETREQUEST,
    output_type=_INTERRUPTGETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEMSVC)

DESCRIPTOR.services_by_name['SystemSvc'] = _SYSTEMSVC

# @@protoc_insertion_point(module_scope)
