# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
try:
  gogo__pb2 = types__pb2.gogo__pb2
except AttributeError:
  gogo__pb2 = types__pb2.gogo_pb2
import events_pb2 as events__pb2
import flow_pb2 as flow__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oper.proto',
  package='operd',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\noper.proto\x12\x05operd\x1a\x0btypes.proto\x1a\x0c\x65vents.proto\x1a\nflow.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n\x0cOperInfoSpec\x12%\n\x08InfoType\x18\x01 \x01(\x0e\x32\x13.operd.OperInfoType\x12!\n\x06\x41\x63tion\x18\x02 \x01(\x0e\x32\x11.operd.OperInfoOp\x12)\n\x0b\x45ventFilter\x18\x03 \x01(\x0b\x32\x12.operd.EventFilterH\x00\x42\r\n\x0binfo_filter\"7\n\x0fOperInfoRequest\x12$\n\x07Request\x18\x01 \x03(\x0b\x32\x13.operd.OperInfoSpec\"\xb2\x01\n\x10OperInfoResponse\x12 \n\x06Status\x18\x01 \x01(\x0e\x32\x10.types.ApiStatus\x12%\n\x08InfoType\x18\x02 \x01(\x0e\x32\x13.operd.OperInfoType\x12!\n\tEventInfo\x18\x03 \x01(\x0b\x32\x0c.operd.EventH\x00\x12%\n\x0b\x46lowLogInfo\x18\x04 \x01(\x0b\x32\x0e.operd.FlowLogH\x00\x42\x0b\n\toper_info*^\n\x0cOperInfoType\x12\x17\n\x13OPER_INFO_TYPE_NONE\x10\x00\x12\x18\n\x14OPER_INFO_TYPE_EVENT\x10\x01\x12\x1b\n\x17OPER_INFO_TYPE_FLOW_LOG\x10\x02*]\n\nOperInfoOp\x12\x15\n\x11OPER_INFO_OP_NONE\x10\x00\x12\x1a\n\x16OPER_INFO_OP_SUBSCRIBE\x10\x01\x12\x1c\n\x18OPER_INFO_OP_UNSUBSCRIBE\x10\x02\x32U\n\x07OperSvc\x12J\n\x11OperInfoSubscribe\x12\x16.operd.OperInfoRequest\x1a\x17.operd.OperInfoResponse\"\x00(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[types__pb2.DESCRIPTOR,events__pb2.DESCRIPTOR,flow__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_OPERINFOTYPE = _descriptor.EnumDescriptor(
  name='OperInfoType',
  full_name='operd.OperInfoType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPER_INFO_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPER_INFO_TYPE_EVENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPER_INFO_TYPE_FLOW_LOG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=480,
  serialized_end=574,
)
_sym_db.RegisterEnumDescriptor(_OPERINFOTYPE)

OperInfoType = enum_type_wrapper.EnumTypeWrapper(_OPERINFOTYPE)
_OPERINFOOP = _descriptor.EnumDescriptor(
  name='OperInfoOp',
  full_name='operd.OperInfoOp',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPER_INFO_OP_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPER_INFO_OP_SUBSCRIBE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPER_INFO_OP_UNSUBSCRIBE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=576,
  serialized_end=669,
)
_sym_db.RegisterEnumDescriptor(_OPERINFOOP)

OperInfoOp = enum_type_wrapper.EnumTypeWrapper(_OPERINFOOP)
OPER_INFO_TYPE_NONE = 0
OPER_INFO_TYPE_EVENT = 1
OPER_INFO_TYPE_FLOW_LOG = 2
OPER_INFO_OP_NONE = 0
OPER_INFO_OP_SUBSCRIBE = 1
OPER_INFO_OP_UNSUBSCRIBE = 2



_OPERINFOSPEC = _descriptor.Descriptor(
  name='OperInfoSpec',
  full_name='operd.OperInfoSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='InfoType', full_name='operd.OperInfoSpec.InfoType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Action', full_name='operd.OperInfoSpec.Action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EventFilter', full_name='operd.OperInfoSpec.EventFilter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='info_filter', full_name='operd.OperInfoSpec.info_filter',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=94,
  serialized_end=240,
)


_OPERINFOREQUEST = _descriptor.Descriptor(
  name='OperInfoRequest',
  full_name='operd.OperInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Request', full_name='operd.OperInfoRequest.Request', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=297,
)


_OPERINFORESPONSE = _descriptor.Descriptor(
  name='OperInfoResponse',
  full_name='operd.OperInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='operd.OperInfoResponse.Status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='InfoType', full_name='operd.OperInfoResponse.InfoType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EventInfo', full_name='operd.OperInfoResponse.EventInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FlowLogInfo', full_name='operd.OperInfoResponse.FlowLogInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='oper_info', full_name='operd.OperInfoResponse.oper_info',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=300,
  serialized_end=478,
)

_OPERINFOSPEC.fields_by_name['InfoType'].enum_type = _OPERINFOTYPE
_OPERINFOSPEC.fields_by_name['Action'].enum_type = _OPERINFOOP
_OPERINFOSPEC.fields_by_name['EventFilter'].message_type = events__pb2._EVENTFILTER
_OPERINFOSPEC.oneofs_by_name['info_filter'].fields.append(
  _OPERINFOSPEC.fields_by_name['EventFilter'])
_OPERINFOSPEC.fields_by_name['EventFilter'].containing_oneof = _OPERINFOSPEC.oneofs_by_name['info_filter']
_OPERINFOREQUEST.fields_by_name['Request'].message_type = _OPERINFOSPEC
_OPERINFORESPONSE.fields_by_name['Status'].enum_type = types__pb2._APISTATUS
_OPERINFORESPONSE.fields_by_name['InfoType'].enum_type = _OPERINFOTYPE
_OPERINFORESPONSE.fields_by_name['EventInfo'].message_type = events__pb2._EVENT
_OPERINFORESPONSE.fields_by_name['FlowLogInfo'].message_type = flow__pb2._FLOWLOG
_OPERINFORESPONSE.oneofs_by_name['oper_info'].fields.append(
  _OPERINFORESPONSE.fields_by_name['EventInfo'])
_OPERINFORESPONSE.fields_by_name['EventInfo'].containing_oneof = _OPERINFORESPONSE.oneofs_by_name['oper_info']
_OPERINFORESPONSE.oneofs_by_name['oper_info'].fields.append(
  _OPERINFORESPONSE.fields_by_name['FlowLogInfo'])
_OPERINFORESPONSE.fields_by_name['FlowLogInfo'].containing_oneof = _OPERINFORESPONSE.oneofs_by_name['oper_info']
DESCRIPTOR.message_types_by_name['OperInfoSpec'] = _OPERINFOSPEC
DESCRIPTOR.message_types_by_name['OperInfoRequest'] = _OPERINFOREQUEST
DESCRIPTOR.message_types_by_name['OperInfoResponse'] = _OPERINFORESPONSE
DESCRIPTOR.enum_types_by_name['OperInfoType'] = _OPERINFOTYPE
DESCRIPTOR.enum_types_by_name['OperInfoOp'] = _OPERINFOOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperInfoSpec = _reflection.GeneratedProtocolMessageType('OperInfoSpec', (_message.Message,), {
  'DESCRIPTOR' : _OPERINFOSPEC,
  '__module__' : 'oper_pb2'
  # @@protoc_insertion_point(class_scope:operd.OperInfoSpec)
  })
_sym_db.RegisterMessage(OperInfoSpec)

OperInfoRequest = _reflection.GeneratedProtocolMessageType('OperInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERINFOREQUEST,
  '__module__' : 'oper_pb2'
  # @@protoc_insertion_point(class_scope:operd.OperInfoRequest)
  })
_sym_db.RegisterMessage(OperInfoRequest)

OperInfoResponse = _reflection.GeneratedProtocolMessageType('OperInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPERINFORESPONSE,
  '__module__' : 'oper_pb2'
  # @@protoc_insertion_point(class_scope:operd.OperInfoResponse)
  })
_sym_db.RegisterMessage(OperInfoResponse)



_OPERSVC = _descriptor.ServiceDescriptor(
  name='OperSvc',
  full_name='operd.OperSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=671,
  serialized_end=756,
  methods=[
  _descriptor.MethodDescriptor(
    name='OperInfoSubscribe',
    full_name='operd.OperSvc.OperInfoSubscribe',
    index=0,
    containing_service=None,
    input_type=_OPERINFOREQUEST,
    output_type=_OPERINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPERSVC)

DESCRIPTOR.services_by_name['OperSvc'] = _OPERSVC

# @@protoc_insertion_point(module_scope)
