IPROUTE2_MLNX_VERSION = 5.10.0
IPROUTE2_MLNX_VERSION_FULL = $(IPROUTE2_MLNX_VERSION)-4~bpo10+1

export IPROUTE2_MLNX_VERSION
export IPROUTE2_MLNX_VERSION_FULL

IPROUTE2_MLNX = iproute2-mlnx_$(IPROUTE2_MLNX_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(IPROUTE2_MLNX)_SRC_PATH = $(PLATFORM_PATH)/iproute2
SONIC_MAKE_DEBS += $(IPROUTE2_MLNX)
