#!/bin/bash

SENSORS_FILE_PREFIX="/usr/share/sonic/platform/sensors"

function get_sensor_conf_path() {
    VERSION=$(python3 -c "import sonic_platform;print(sonic_platform.device_data.DeviceDataManager.get_hardware_version())")
    if [[ "$VERSION" == "" ]]; then
        echo "${SENSORS_FILE_PREFIX}.conf"
    else
        echo "${SENSORS_FILE_PREFIX}_${VERSION}.conf"
    fi
}

get_sensor_conf_path
