#!/usr/bin/python3
import sys
from sonic_platform.device_data import DeviceDataManager
from sonic_py_common.logger import Logger


logger = Logger(log_identifier='platform_wait')
logger.log_notice('Nvidia: Wait for PMON dependencies to be ready')
if DeviceDataManager.wait_platform_ready():
    logger.log_notice('Nvidia: PMON dependencies are ready')
    sys.exit(0)
else:
    logger.log_error('Nvidia: PMON dependencies are not ready: timeout')
    sys.exit(-1)
