#!/bin/bash

### BEGIN INIT INFO
# Provides:          setup-board
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Setup ag7648v2 board.
### END INIT INFO

install_python_api_package() {
    device="/usr/share/sonic/device"
    platform=$(/usr/local/bin/sonic-cfggen -H -v DEVICE_METADATA.localhost.platform)

    rv=$(pip install $device/$platform/sonic_platform-1.0-py2-none-any.whl)
    rv=$(pip3 install $device/$platform/sonic_platform-1.0-py3-none-any.whl)
}

remove_python_api_package() {
    rv=$(pip show sonic-platform > /dev/null 2>/dev/null)
    if [ $? -eq 0 ]; then
        rv=$(pip uninstall -y sonic-platform > /dev/null 2>/dev/null)
    fi

    rv=$(pip3 show sonic-platform > /dev/null 2>/dev/null)
    if [ $? -eq 0 ]; then
        rv=$(pip3 uninstall -y sonic-platform > /dev/null 2>/dev/null)
    fi
}

case "$1" in
start)
    echo -n "Setting up board... "
    depmod -a
    rmmod i2c-i801
    rmmod i2c-ismt
    modprobe i2c-dev
    modprobe i2c-i801
    modprobe i2c-ismt
    modprobe i2c-mux
    modprobe i2c-mux-gpio
    modprobe i2c-mux-pca954x
    modprobe dni_ag7648v2_psu
    modprobe dni_emc2305
    modprobe at24
    modprobe optoe
    modprobe eeprom

# Enable I2C MUX all channel (addr: 0x70, reg:0x0, value: 0xFF)
    i2cset -f -y 1 0x70 0x0 0xFF
    modprobe delta_ag7648v2_platform
    sync;sync;sync;sync
    modprobe delta_ag7648v2_swpld
    modprobe delta_ag7648v2_sfp
    /usr/local/bin/ag7648v2_platform_init.sh
    install_python_api_package
    mkdir $device/$platform/pddf_support
    ln -s $device/$platform/ /usr/share/sonic/platform

    echo "done."
    ;;

stop)
    remove_python_api_package
    echo "done."

    ;;

force-reload|restart)
    echo "Not supported"
    ;;

*)
    echo "Usage: /etc/init.d/platform-modules-ag7648v2.init {start|stop}"
    exit 1
    ;;
esac

exit 0
