#!/bin/bash

### BEGIN INIT INFO
# Provides:          setup-board
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Setup ag9032v2a board.
### END INIT INFO

install_python_api_package() {
    device="/usr/share/sonic/device"
    platform=$(/usr/local/bin/sonic-cfggen -H -v DEVICE_METADATA.localhost.platform)

    rv=$(pip install $device/$platform/sonic_platform-1.0-py2-none-any.whl)
    rv=$(pip3 install $device/$platform/sonic_platform-1.0-py3-none-any.whl)
}

remove_python_api_package() {
    rv=$(pip show sonic-platform > /dev/null 2>/dev/null)
    if [ $? -eq 0 ]; then
        rv=$(pip uninstall -y sonic-platform > /dev/null 2>/dev/null)
    fi

    rv=$(pip3 show sonic-platform > /dev/null 2>/dev/null)
    if [ $? -eq 0 ]; then
        rv=$(pip3 uninstall -y sonic-platform > /dev/null 2>/dev/null)
    fi
}

case "$1" in
start)
    echo -n "Setting up board... "
    depmod -a
    rmmod i2c-i801
    rmmod i2c-ismt
    modprobe i2c-dev
    modprobe i2c-i801
    modprobe i2c-ismt
    modprobe ipmi_devintf
    modprobe ipmi_si ports=0xca2
    modprobe optoe
    modprobe delta_ag9032v2_platform
    /usr/local/bin/ag9032v2_platform_init.sh
    install_python_api_package

    echo "done."
    ;;

stop)
    remove_python_api_package
    echo "done."

    ;;

force-reload|restart)
    echo "Not supported"
    ;;

*)
    echo "Usage: /etc/init.d/platform-modules-ag9032v2.init {start|stop}"
    exit 1
    ;;
esac

exit 0
