#!/bin/sh

mr_reboot() {

    sudo rmmod x86-64-netberg-aurora-615
    sudo i2cset -y 0 0x30 0xa1 0  

}

if [ $# -eq 0 ] || [ $@ = "-r" ] || [ $@ = "--reboot" ] || [ $@ = "-h" ] || [ $@ = "-P" ] || [ $@ = "--poweroff" ]; then
    sync;sync
    mr_reboot
elif [ $@ = "-H" ] || [ $@ = "--halt" ]; then
    sudo halt
else
    echo "unsupported option"
fi

