ruijie_common-objs := ruijie_common_module.o dfd_tlveeprom.o
obj-m := ruijie_b6510_platform.o rg-gpio-xeon.o 
obj-m += rg_fan.o 
obj-m += rg_psu.o
obj-m += ruijie_platform.o
obj-m += i2c-mux-pca9641.o
obj-m += i2c-mux-pca954x.o
obj-m += csu550.o
obj-m += ruijie_common.o

