#!/bin/bash
snmp_user=snmp

#TODO: check with sasha whether this file will be generated by base image or in container
sonic-cfggen -m /etc/sonic/minigraph.xml -v /etc/sonic/var.yml -t /etc/swss/snmp/sysDescription.j2 >/etc/ssw/sysDescription

sonic-cfggen -a '{"snmp_user":"'$snmp_user'"}' -t /etc/swss/snmp/snmpd.j2 >/etc/default/snmpd

sonic-cfggen -m /etc/sonic/minigraph.xml -v /etc/sonic/var.yml -t /etc/swss/snmp/snmpd.conf.j2 >/etc/snmp/snmpd.conf

hwsku=`sonic-cfggen -m /etc/sonic/minigraph.xml -v minigraph_hwsku`
/bin/cp -rf /usr/share/sonic/$hwsku/alias_map.json /etc/snmp/


