#!/bin/bash
if dpkg-query -W --showformat='${Version}' snmp |grep -q "5.7.2"; then
  snmp_user=snmp
else
  snmp_uesr=Debian-snmp
fi

#TODO: check with sasha whether this file will be generated by base image or in container
sonic-cfggen -m /etc/sonic/minigraph.xml -v /etc/sonic/var/yml -t /etc/swss/snmp/sysDescription.j2 >etc/ssw/sysDescription

sonic-cfggen -a '{"snmp_user":"'$snmp_user'"}' -t /etc/swss/snmp/snmpd.j2 >/etc/default/snmpd

sonic-cfggen -m /etc/sonic/minigraph.xml -v /etc/sonic/var.yml -t /etc/swss/snmp/snmpd.conf.j2 >etc/snmp/snmpd.conf

hwsku=`sonic-cfggen -m /etc/sonic/minigraph.xml -v minigraph_hwsku`
/bin/cp -rf /usr/share/sonic/$hwsku/alias_map.json /etc/snmp/


