# postinst script for Netberg devices

# Unload hardware monitoring module, if any
modprobe -q -r hardware_monitor ||:

# Unload modules required for hardware monitoring
modprobe -q -r i2c-mux-pca954x ||:
modprobe -q -r i2c-mux-gpio ||:
modprobe -q -r i2c-mux ||:

modprobe -q -r i2c-isch ||:
modprobe -q -r i2c-ismt ||:
modprobe -q -r i2c-i801 ||:
modprobe -q -r i2c-smbus ||:

modprobe -q -r i2c-dev ||:

#DEBHELPER#

# Load hardware monitoring module
modprobe -q hardware_monitor ||:

# Make sure modprobe.d(5) is in initramfs
update-initramfs -u
