TARGET:= pddf_custom_fan_driver_module
$(TARGET)-objs := ./fan_driver/pddf_custom_fan_api.o ./fan_driver/pddf_custom_fan_driver.o

obj-m := $(TARGET).o
obj-m += pddf_custom_fpga_algo.o pddf_custom_fpga_extend.o 
