.ONESHELL:
SHELL = /bin/bash
.SHELLFLAGS += -e

MAIN_TARGET = $(FRR)
DERIVED_TARGET = $(FRR_PYTHONTOOLS) $(FRR_DBG) $(FRR_SNMP) $(FRR_SNMP_DBG)
SUFFIX = $(shell date +%Y%m%d\.%H%M%S)
STG_BRANCH = stg_temp.$(SUFFIX)

$(addprefix $(DEST)/, $(MAIN_TARGET)): $(DEST)/% :
	# Build the package
	pushd ./frr
	# delete previously created temporary branches, if any
	git checkout master
	git branch | grep stg_temp | xargs --no-run-if-empty git branch -D
	if [ `git branch | grep $(FRR_BRANCH)` ]
	then
		echo "Branch named $(FRR_BRANCH) already exists"
		git branch -D $(FRR_BRANCH)
	else
		echo "Branch named $(FRR_BRANCH) does not exist"
	fi
	git checkout -b $(FRR_BRANCH) origin/$(FRR_BRANCH)
	stg branch --create $(STG_BRANCH) $(FRR_TAG)
	stg import -s ../patch/series
	tools/tarsource.sh -V -e '-sonic'
	dpkg-buildpackage -rfakeroot -b -us -uc -Ppkg.frr.nortrlib -j$(SONIC_CONFIG_MAKE_JOBS)
	stg undo || true
	git clean -xfdf
	git checkout $(FRR_BRANCH)
	stg branch --delete $(STG_BRANCH)
	git rev-parse --short HEAD | xargs git checkout
	git checkout master
	git branch -D $(FRR_BRANCH)
	popd
	mv $(DERIVED_TARGET) $* $(DEST)/

$(addprefix $(DEST)/, $(DERIVED_TARGET)): $(DEST)/% : $(DEST)/$(MAIN_TARGET)
