#!/usr/bin/python

def main():
    # reboot the system
    with open('/sys/class/gpio/export', 'w') as file:
        file.write('502')
    with open('/sys/class/gpio/gpio502/direction', 'w') as file:
        file.write('out')
    with open('/sys/class/gpio/gpio502/value', 'w') as file:
        file.write('1')

if __name__ == "__main__":
    main()
