# PDDF Generic Platform modules
####################################################
PDDF_PLATFORM_MODULE_VERSION = 1.1

export PDDF_PLATFORM_MODULE_VERSION

PDDF_PLATFORM_MODULE = sonic-platform-pddf_$(PDDF_PLATFORM_MODULE_VERSION)_amd64.deb
$(PDDF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PDDF_PATH)/i2c
$(PDDF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(PDDF_PLATFORM_MODULE)

ifneq ($(SONIC_ONE_IMAGE),)
$(SONIC_ONE_IMAGE)_INSTALLS += $(PDDF_PLATFORM_MODULE)
endif

ifneq ($(SONIC_ONE_PDE_IMAGE),)
$(SONIC_ONE_PDE_IMAGE)_INSTALLS += $(PDDF_PLATFORM_MODULE)
endif

SONIC_STRETCH_DEBS += $(PDDF_PLATFORM_MODULE)
