
{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

RUN apt-get update

{% if docker_pac_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_pac_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_pac_debs.split(' ')) }}
{%- endif %}

RUN apt-get clean -y      && \
    apt-get autoclean -y  && \
    apt-get autoremove -y && \
    apt-get install systemctl -y && \
    rm -rf /debs

# For click framework 
RUN pip3 install click 

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor"]

#labels for yang
#LABEL com.azure.sonic.yang-module.sonic-pac="/usr/local/yang-models/sonic-pac.yang"

ENTRYPOINT ["/usr/local/bin/supervisord"]
