#!/bin/bash

### BEGIN INIT INFO
# Provides:          setup-board
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Setup ly1200-32x board.
### END INIT INFO

case "$1" in
start)
    echo -n "Setting up board... "

    echo 0 > /proc/sys/kernel/perf_cpu_time_max_percent
    /etc/init.d/i2c_init start
    /etc/init.d/sys_polld start
    /etc/init.d/sys_servd start
    echo 0 > /sys/bus/i2c/devices/1-0031/wd_en
    echo "0x0" > /sys/bus/i2c/devices/1-0032/port_1_8_modsel
    echo "0x0" > /sys/bus/i2c/devices/1-0032/port_9_16_modsel
    echo "0x0" > /sys/bus/i2c/devices/1-0033/port_17_24_modsel
    echo "0x0" > /sys/bus/i2c/devices/1-0033/port_25_32_modsel
    echo "0x0" > /sys/bus/i2c/devices/1-0032/port_1_8_lpmode
    echo "0x0" > /sys/bus/i2c/devices/1-0032/port_9_16_lpmode
    echo "0x0" > /sys/bus/i2c/devices/1-0033/port_17_24_lpmode
    echo "0x0" > /sys/bus/i2c/devices/1-0033/port_25_32_lpmode
    echo "0xff" > /sys/bus/i2c/devices/1-0032/port_1_8_rst
    echo "0xff" > /sys/bus/i2c/devices/1-0032/port_9_16_rst
    echo "0xff" > /sys/bus/i2c/devices/1-0033/port_17_24_rst
    echo "0xff" > /sys/bus/i2c/devices/1-0033/port_25_32_rst

    echo "done."
    ;;

stop)
    echo -n "cleaning... "

    /etc/init.d/i2c_init stop
    /etc/init.d/sys_servd stop
    /etc/init.d/sys_polld stop

    echo "done."
    ;;

force-reload|restart)
    echo "Not supported"
    ;;

*)
    echo "Usage: /etc/init.d/sonic-platform-mitac-ly1200-32x {start|stop}"
    exit 1
    ;;
esac

exit 0
