#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
        if [ -x "/etc/init.d/sonic-platform-mitac-ly1200-32x" ]; then
                update-rc.d xcvr_servd defaults >/dev/null
                update-rc.d sonic-platform-mitac-ly1200-32x defaults >/dev/null
                invoke-rc.d sonic-platform-mitac-ly1200-32x start || exit $?
        fi
fi
# End automatically added section
