#!/bin/sh

set -e

if [ -n "${IF_PEER_NETNS}" -a -n "${IF_PEER_IFACE}" ]
then
	if OUTPUT=$(ip netns list | grep -w ${IF_PEER_NETNS})
	then
		# Take down the remote end of the veth
		ip netns exec ${IF_PEER_NETNS} ip link set ${IF_PEER_IFACE} down

		case "${IF_CONFIGURE_INTERFACES}" in
			true|yes|on)
				# Ifdown the interfaces inside the netns and inside
				# a mount namespace with /run/network.nsname mounted
				# on /run/network
				unshare -m /bin/sh <<-EOF
					mount --make-rprivate /
					mount --bind /run/network.${IF_PEER_NETNS} /run/network
					/usr/bin/delete-mgmt-vrf-iptables.sh

            	    logger "if_down_netns: Doing ifdown for the interfaces present in management namespace."
					ip netns exec ${IF_PEER_NETNS} ifdown -i /etc/network/interfaces.${IF_PEER_NETNS} -a
				EOF
				;;
		esac
	fi
fi
