{% from "dockers/dockerfile-macros.j2" import install_debian_packages %}
FROM docker-config-engine-buster

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

COPY \
{% for deb in docker_syncd_brcm_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

# Install dependencies for libsaibcm debian packages
{%- set syncd_brcm_debs = [] %}
{% for deb in docker_syncd_brcm_debs.split(' ') -%}
{%- if 'libsaibcm' in deb %}
RUN apt-get install -y $(dpkg --info debs/{{ deb }} | grep Depends | sed "s/.*ends:\ //" | tr '\n' ' ' | tr ',' ' ')
{%- else %}
{{- syncd_brcm_debs.append(deb) or '' }}
{%- endif %}
{%- endfor %}

# To store saibcm debian packages
RUN mkdir /usr/local/debs

# Move the saibcm debian packages
RUN mv debs/libsaibcm*_amd64.deb /usr/local/debs

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(syncd_brcm_debs) }}

## TODO: add kmod into Depends
RUN apt-get install -yf kmod

## BRCM uses ethtool to set host interface speed
RUN apt-get install -y ethtool

COPY ["files/dsserve", "files/bcmcmd", "start.sh", "start_led.sh", "bcmsh", "/usr/bin/"]
RUN chmod +x /usr/bin/dsserve /usr/bin/bcmcmd

COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor/"]

## Clean up
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

ENTRYPOINT ["/usr/local/bin/supervisord"]
