# sonic broadcom one image installer

SONIC_ONE_PDE_IMAGE = sonic-broadcom-pde.bin
$(SONIC_ONE_PDE_IMAGE)_MACHINE = broadcom
$(SONIC_ONE_PDE_IMAGE)_IMAGE_TYPE = onie
$(SONIC_ONE_PDE_IMAGE)_INSTALLS += $(BRCM_OPENNSL_KERNEL)
$(SONIC_ONE_PDE_IMAGE)_INSTALLS += $(PDDF_PLATFORM_MODULE)
$(SONIC_ONE_PDE_IMAGE)_LAZY_INSTALLS += $(SONIC_ONE_IMAGE_LAZY_INSTALLS)

$(SONIC_ONE_PDE_IMAGE)_DOCKERS += $(DOCKER_PDE) $(DOCKER_PLATFORM_MONITOR) $(DOCKER_DATABASE)
SONIC_INSTALLERS += $(SONIC_ONE_PDE_IMAGE)
