# Netberg Platform modules

NETBERG_PLATFORM_MODULE_VERSION = 0.6

export NETBERG_PLATFORM_MODULE_VERSION

NETBERG_PLATFORM_MODULE = platform-modules-netberg_$(NETBERG_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-netberg
$(NETBERG_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(NETBERG_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_420_rangeley-r0
SONIC_DPKG_DEBS += $(NETBERG_PLATFORM_MODULE)

SONIC_STRETCH_DEBS += $(NETBERG_PLATFORM_MODULE)
