NETBERG_AURORA_221_PLATFORM_MODULE_VERSION = 1.0.1
NETBERG_AURORA_621_PLATFORM_MODULE_VERSION = 1.0.1
NETBERG_AURORA_721_PLATFORM_MODULE_VERSION = 1.0.1
NETBERG_AURORA_830_PLATFORM_MODULE_VERSION = 1.0.1

export NETBERG_AURORA_221_PLATFORM_MODULE_VERSION
export NETBERG_AURORA_621_PLATFORM_MODULE_VERSION
export NETBERG_AURORA_721_PLATFORM_MODULE_VERSION
export NETBERG_AURORA_830_PLATFORM_MODULE_VERSION

NETBERG_AURORA_221_PLATFORM_MODULE = sonic-platform-netberg-aurora-221_$(NETBERG_AURORA_221_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_221_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-netberg
$(NETBERG_AURORA_221_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(NETBERG_AURORA_221_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_221-r0
SONIC_DPKG_DEBS += $(NETBERG_AURORA_221_PLATFORM_MODULE)

NETBERG_AURORA_621_PLATFORM_MODULE = sonic-platform-netberg-aurora-621_$(NETBERG_AURORA_621_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_621_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_621-r0
$(eval $(call add_extra_package,$(NETBERG_AURORA_221_PLATFORM_MODULE),$(NETBERG_AURORA_621_PLATFORM_MODULE)))

NETBERG_AURORA_721_PLATFORM_MODULE = sonic-platform-netberg-aurora-721_$(NETBERG_AURORA_721_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_721_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_721-r0
$(eval $(call add_extra_package,$(NETBERG_AURORA_221_PLATFORM_MODULE),$(NETBERG_AURORA_721_PLATFORM_MODULE)))

NETBERG_AURORA_830_PLATFORM_MODULE = sonic-platform-netberg-aurora-830_$(NETBERG_AURORA_830_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_830_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_830-r0
$(eval $(call add_extra_package,$(NETBERG_AURORA_221_PLATFORM_MODULE),$(NETBERG_AURORA_830_PLATFORM_MODULE)))
