# UfiSpace Platform modules

NETBERG_AURORA_221_PLATFORM_MODULE_VERSION = 1.0.0

export NETBERG_AURORA_221_PLATFORM_MODULE_VERSION

NETBERG_AURORA_221_PLATFORM_MODULE = sonic-platform-netberg-aurora-221_$(NETBERG_AURORA_221_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_221_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-netberg
$(NETBERG_AURORA_221_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(NETBERG_AURORA_221_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_221-r0
SONIC_DPKG_DEBS += $(NETBERG_AURORA_221_PLATFORM_MODULE)
