# Broadcom SAI modules

BRCM_OPENNSL_KERNEL_VERSION = 5.0.0.1

BRCM_OPENNSL_KERNEL = opennsl-modules_$(BRCM_OPENNSL_KERNEL_VERSION)_amd64.deb
$(BRCM_OPENNSL_KERNEL)_SRC_PATH = $(PLATFORM_PATH)/saibcm-modules
$(BRCM_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
ifeq ($(ASIC_FAMILY),dnx)
$(BRCM_OPENNSL_KERNEL)_BUILD_ENV = ASIC_FAMILY=dnx
endif
SONIC_DPKG_DEBS += $(BRCM_OPENNSL_KERNEL)
