# Broadcom SAI modules

BRCM_OPENNSL_KERNEL_VERSION = 4.3.0.10-2

BRCM_OPENNSL_KERNEL = opennsl-modules_$(BRCM_OPENNSL_KERNEL_VERSION)_amd64.deb
$(BRCM_OPENNSL_KERNEL)_SRC_PATH = $(PLATFORM_PATH)/saibcm-modules
$(BRCM_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_OPENNSL_KERNEL)_BUILD_ENV = PKG_NAME=$(BRCM_OPENNSL_KERNEL)
SONIC_DPKG_DEBS += $(BRCM_OPENNSL_KERNEL)
