#!/bin/sh

case $1 in
    prereqs)
        exit 0
        ;;
esac

# Extract kernel parameters
root_val=""
set -- $(cat /proc/cmdline)
for x in "$@"; do
    case "$x" in
        root=*)
            root_val="${x#root=}"
            ;;
    esac
done

# Check the filesystem we are using
if [ ! -z $root_val ]; then
    fstype=$(blkid -o value -s TYPE $root_val)
    case "$fstype" in
        ext4)
            fsck.ext4 -p $root_val
            ;;
        ext3)
            fsck.ext3 -p $root_val
            ;;
    esac
fi
