#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

# reconstruct the MAC address to 16bytes and output to /run/machine-id
sed 's/:/0000/g' /sys/class/net/eth0/address > /run/machine-id