#!/bin/sh

case $1 in
    prereqs)
        exit 0
        ;;
esac

# Extract kernel parameters
set -- $(cat /proc/cmdline)
for x in "$@"; do
    case "$x" in
        root=*)
            root_dev="${x#root=}"
            ;;
        resize-rootfs)
            [ -z "$root_dev" ] && exit 0
            resize2fs -f $root_dev
            if [ $? != 0 ]; then
                echo "ERROR: Unable to resize the root file system. Manual intervention needed to fix the issue."
            fi
            ;;
    esac
done
