obj-m := x86-64-netberg-aurora-615.o
x86-64-netberg-aurora-615-objs := x86-64-netberg-aurora-615-common.o x86-64-netberg-aurora-615-sys.o \
x86-64-netberg-aurora-615-led.o x86-64-netberg-aurora-615-fan.o x86-64-netberg-aurora-615-power.o \
x86-64-netberg-aurora-615-thermal.o x86-64-netberg-aurora-615-qsfp.o x86-64-netberg-aurora-615-sfp.o
