# docker image for cavm saiserver

DOCKER_SAISERVER_CAVM = docker-saiserver-cavm.gz
$(DOCKER_SAISERVER_CAVM)_PATH = $(PLATFORM_PATH)/docker-saiserver-cavm
$(DOCKER_SAISERVER_CAVM)_FILES += $(SAISERVER)
$(DOCKER_SAISERVER_CAVM)_LOAD_DOCKERS += $(DOCKER_BASE)
SONIC_DOCKER_IMAGES += $(DOCKER_SAISERVER_CAVM)
