#!/usr/bin/python
import json
import os

database_config_file = "/etc/sonic/database_config.json"

with open(database_config_file, "r") as read_file:
    data = json.load(read_file)

if 'DATABASE' in data:
    for inst in data["DATABASE"]:
        port = data["DATABASE"][inst]["port"]
        os.system("ping_pong_single_db_inst.sh " + str(port))
# if nothing configured, there is a default redis server
else:
    os.system("ping_pong_single_db_inst.sh 6379")
