# Special arrangement to make PDDF mode default
# Disable monitor, monitor-fan, monitor-psu (not enabling them would imply they will be disabled by default)
# Enable pddf-platform-monitor

depmod -a
systemctl enable n8550-platform-handle_mac.service
systemctl start n8550-platform-handle_mac.service
systemctl enable pddf-platform-init.service
systemctl start pddf-platform-init.service
systemctl enable n8550-48b8c-pddf-platform-monitor.service
systemctl start n8550-48b8c-pddf-platform-monitor.service
