#!/bin/bash

IMAGENAME=$1

. /usr/local/share/buildinfo/scripts/buildinfo_base.sh


[ -d $POST_VERSION_PATH ] && rm -rf $POST_VERSION_PATH

# Collect the version files
collect_version_files $POST_VERSION_PATH

#Save the cache file for exporting it to host.
tar -C ${PKG_CACHE_PATH} --exclude=cache.tgz -zcvf /cache.tgz .

