#!/bin/bash

if [ "$reason" = BOUND ]  &&  ["$reason" != RENEW ] \
   && ["$reason" != REBIND ]  &&  ["$reason" != REBOOT ]
then
    exit 0
fi

current_host_name=`hostname -s`

if [ "$current_host_name" != "$new_host_name" ] && [ ! -z "$new_host_name" ]
then
    echo $new_host_name > /etc/hostname
    hostname -F /etc/hostname
    sed -i "/\s$current_host_name$/d" /etc/hosts
    echo "127.0.0.1 $new_host_name" >> /etc/hosts
fi


