{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-stretch

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

RUN echo

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

## Install redis-tools dependencies
## TODO: implicitly install dependencies
RUN apt-get update        \
&& apt-get install -f -y \
       libdbus-1-3       \
       libdaemon0        \
       libjansson4       \
       libpython2.7      \
       libatomic1        \
       libjemalloc1      \
       liblua5.1-0       \
       lua-bitop         \
       lua-cjson         \
       libelf1           \
       libmnl0           \
       bridge-utils      \
       conntrack

COPY \
{% for deb in docker_nat_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN dpkg -i \
{% for deb in docker_nat_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["restore_nat_entries.py", "/usr/bin/"]

RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

ENTRYPOINT ["/usr/bin/supervisord"]

