obj-m += lpc_ich.o
obj-m += i2c-mux-pca9541.o
obj-m += inv_psu.o
obj-m += inv_tmp75.o
obj-m += inv_ucd90160.o
obj-m += inv_cpld.o
obj-m += inv_psoc.o
obj-m += inv_platform.o
obj-m += inv_eeprom.o
obj-m += inv_pthread.o
obj-m += swps.o
swps-objs := inv_swps.o inv_mux.o io_expander.o transceiver.o

