{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
ARG BASE=docker-syncd-brcm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE as base

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get purge -y syncd

## Pre-install the fundamental packages
RUN apt-get update \
 && apt-get -y install  \
    net-tools           \
    python3-pip          \
    python-setuptools   \
    build-essential     \
    libssl-dev          \
    libffi-dev          \
    python-dev          \
    wget                \
    cmake

{% if docker_syncd_brcm_rpc_debs.strip() -%}
# Copy built Debian packages
{{ copy_files("debs/", docker_syncd_brcm_rpc_debs.split(' '), "/debs/") }}

# Install built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_syncd_brcm_rpc_debs.split(' ')) }}
{%- endif %}

RUN wget https://github.com/nanomsg/nanomsg/archive/1.0.0.tar.gz \
 && tar xvfz 1.0.0.tar.gz \
 && cd nanomsg-1.0.0    \
 && mkdir -p build      \
 && cmake .             \
 && make install        \
 && ldconfig            \
 && cd ..               \
 && rm -fr nanomsg-1.0.0 \
 && rm -f 1.0.0.tar.gz  \
 && pip2 install cffi==1.7.0    \
 && pip2 install --upgrade cffi==1.7.0 \
 && pip2 install wheel  \
 && pip2 install nnpy   \
 && mkdir -p /opt       \
 && cd /opt             \
 && wget https://raw.githubusercontent.com/p4lang/ptf/master/ptf_nn/ptf_nn_agent.py \
 && apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y \
 && rm -rf /root/deps

COPY ["ptf_nn_agent.conf", "/etc/supervisor/conf.d/"]

FROM $BASE

COPY --from=base / /

ENV DEBIAN_FRONTEND=noninteractive
ENTRYPOINT ["/usr/local/bin/supervisord"]
