# Clounix Platform modules

VERSION = 1.0.1

CLOUNIX_MODULE = clounix-modules_$(VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_MODULE)_SRC_PATH = $(PLATFORM_PATH)/clounix-modules
$(CLOUNIX_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(CLOUNIX_MODULE)
