# Supermicro SSE-G3748 (using AC5X) Platform modules 

SUPERMICRO_SSE_G3748_PLATFORM_MODULE_VERSION=1.0

export SUPERMICRO_SSE_G3748_PLATFORM_MODULE_VERSION

ifeq ($(CONFIGURED_ARCH),arm64)

SUPERMICRO_SSE_G3748_PLATFORM = sonic-platform-supermicro-sse-g3748_$(SUPERMICRO_SSE_G3748_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(SUPERMICRO_SSE_G3748_PLATFORM)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-supermicro
$(SUPERMICRO_SSE_G3748_PLATFORM)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(SUPERMICRO_SSE_G3748_PLATFORM)_PLATFORM = arm64-supermicro_sse_g3748-r0
SONIC_DPKG_DEBS += $(SUPERMICRO_SSE_G3748_PLATFORM)
$(eval $(call add_extra_package,$(SUPERMICRO_SSE_G3748_PLATFORM)))

endif
