#!/bin/bash

while [ ! -f /etc/sonic/graph_service_url ]; do
    echo "No graph service url speficied, waiting for DHCP response..."
    sleep 1
done

if [ `cat /etc/sonic/graph_service_url` = "disabled" ]; then
    echo "Graph service url not included in DHCP response, skip minigraph downloading"
    exit 0
fi

if [ -f /etc/sonic/minigraph.xml ]; then
    echo "Renaming minigraph.xml to minigraph.old"
    mv /etc/sonic/minigraph.xml /etc/sonic/minigraph.old
fi

HOSTNAME=`hostname -s`
GRAPH_URL=`sonic-cfggen -t /etc/sonic/graph_service_url -a "{\"hostname\": \"$HOSTNAME\"}"`
echo "Getting minigraph from $GRAPH_URL"

while true; do
    curl -f $GRAPH_URL -o /etc/sonic/minigraph.xml --connect-timeout 15 && break
    sleep 5
done
