/*
 * Copyright 2024 Broadcom Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef DEFAULTCONFIG_H
#define DEFAULTCONFIG_H

/* Start of NIM Component's Factory Defaults */

#define FD_NIM_MACTYPE                  SYSMAC_BIA
#define FD_NIM_IF_ALIAS                ""
#define FD_NIM_ADMIN_STATE              DISABLE
#define FD_NIM_SOFT_SHUT_STATE          DISABLE
#define FD_NIM_TRAP_STATE               ENABLE
#define FD_NIM_NAME_TYPE                SYSNAME
#define FD_NIM_FAST_ENET_SPEED          PORTCTRL_PORTSPEED_FULL_100TX
#define FD_NIM_FAST_ENET_FX_SPEED       PORTCTRL_PORTSPEED_FULL_100FX
#define FD_NIM_GIG_ENET_SPEED           PORTCTRL_PORTSPEED_FULL_1000SX
#define FD_NIM_2P5G_ENET_SPEED          PORTCTRL_PORTSPEED_FULL_2P5FX
#define FD_NIM_NO_NEG_2P5G_ENET_SPEED   PORTCTRL_PORTSPEED_FULL_2P5FX
#define FD_NIM_5G_ENET_SPEED            PORTCTRL_PORTSPEED_FULL_5FX
#define FD_NIM_NO_NEG_5G_ENET_SPEED     PORTCTRL_PORTSPEED_FULL_5FX
#define FD_NIM_10G_ENET_SPEED           PORTCTRL_PORTSPEED_FULL_10GSX
#define FD_NIM_20G_ENET_SPEED           PORTCTRL_PORTSPEED_FULL_20GSX
#define FD_NIM_25G_ENET_SPEED           PORTCTRL_PORTSPEED_FULL_25GSX
#define FD_NIM_40G_ENET_SPEED           PORTCTRL_PORTSPEED_FULL_40GSX
#define FD_NIM_50G_ENET_SPEED           PORTCTRL_PORTSPEED_FULL_50GSX
#define FD_NIM_100G_ENET_SPEED          PORTCTRL_PORTSPEED_FULL_100GSX
#define FD_NIM_200G_ENET_SPEED          PORTCTRL_PORTSPEED_FULL_200GSX
#define FD_NIM_400G_ENET_SPEED          PORTCTRL_PORTSPEED_FULL_400GSX
#define FD_NIM_NO_NEG_10G_ENET_SPEED    PORTCTRL_PORTSPEED_FULL_10GSX
#define FD_NIM_OTHER_PORT_TYPE_SPEED    PORTCTRL_PORTSPEED_UNKNOWN
#define FD_NIM_ENCAPSULATION_TYPE       ENCAP_ETHERNET


#define FD_NIM_DEFAULT_ACTIVE_MEDIUM      PORT_MEDIUM_COPPER
#define FD_NIM_DEFAULT_MTU_SIZE           1500

#define FD_DOT3AD_ADMIN_MODE               ENABLE
#define FD_DOT3AD_LINK_TRAP_MODE           DISABLE

#define FD_DOT1Q_DEFAULT_VLAN_INTF_SPEED   PORTCTRL_PORTSPEED_HALF_10T
#define FD_NIM_DEFAULT_LINK_TRAINING_MODE  ENABLE

#define FD_NIM_DEFAULT_COMBO_FORCE              FALSE
#define FD_NIM_DEFAULT_COMBO_PREFER             NIM_COMBO_PREF_SFP

#define FD_NIM_DEFAULT_INTERFACE_FORWARD_ERROR_CORRECTION_MODE         ENABLE


/* End of NIM Component's Factory Defaults */

/*authmgr defaults */
#define FD_MAX_RADIUS_SERVERS        8
#define FD_AUTHMGR_RESTART_TIMER_VAL 2 
#define  AUTHMGR_METHOD_MIN   0
#define  AUTHMGR_METHOD_MAX    AUTHMGR_METHOD_LAST-1 
#define  AUTHMGR_METHOD_START   ( AUTHMGR_METHOD_MIN + 1)
#define FD_AUTHMGR_GLOBAL_MODE   DISABLE
#define FD_AUTHMGR_METHOD   AUTHMGR_METHOD_NONE
#define FD_AUTHMGR_METHOD1   AUTHMGR_METHOD_8021X
#define FD_AUTHMGR_METHOD2   AUTHMGR_METHOD_MAB
#define FD_AUTHMGR_METHOD3   AUTHMGR_METHOD_CP
#define FD_AUTHMGR_OPEN_AUTHENTICATION   DISABLE
#define FD_AUTHMGR_MSG_COUNT    1024

#define FD_AUTHMGR_LIST {  AUTHMGR_METHOD_8021X,  AUTHMGR_METHOD_MAB,  AUTHMGR_METHOD_NONE}

#define FD_AUTHMGR_ADMIN_MODE                        ENABLE
#define FD_AUTHMGR_PORT_MODE                         AUTHMGR_PORT_FORCE_AUTHORIZED
#define FD_AUTHMGR_HOST_MODE                         AUTHMGR_MULTI_HOST_MODE
#define FD_AUTHMGR_PORT_PAE_CAPABILITIES             DOT1X_PAE_PORT_NONE_CAPABLE
#define FD_AUTHMGR_LOG_TRACE_MODE                 DISABLE
#define FD_AUTHMGR_VLAN_ASSIGN_MODE               ENABLE
#define FD_AUTHMGR_DYNAMIC_VLAN_CREATION_MODE     DISABLE
#define FD_AUTHMGR_PORT_DIRECTION                    AUTHMGR_PORT_DIRECTION_BOTH
#define FD_AUTHMGR_PORT_QUIET_PERIOD                60 /* seconds */
#define FD_AUTHMGR_PORT_GUEST_VLAN                  0
#define FD_AUTHMGR_PORT_INACTIVITY_PERIOD           300 /* seconds */
#define FD_AUTHMGR_PORT_METHOD_NO_RESP_PERIOD       ((90*FD_MAX_RADIUS_SERVERS) + 30)  /* seconds */
#define FD_AUTHMGR_PORT_REAUTH_PERIOD               3600 /* seconds */
#define FD_AUTHMGR_PORT_REAUTH_ENABLED               FALSE
#define FD_AUTHMGR_PORT_REAUTH_PERIOD_FROM_SERVER    AUTHMGR_PORT_REAUTH_PERIOD_FROM_SERVER
#define FD_AUTHMGR_PORT_KEY_TRANSMISSION_ENABLED     FALSE
#define FD_AUTHMGR_PORT_MAX_USERS                   48
#define FD_AUTHMGR_PORT_UNAUTHENTICATED_VLAN        0
#define FD_AUTHMGR_PORT_MAB_ENABLED                  DISABLE
#define FD_AUTHMGR_PORT_MAB_AUTH_TYPE                AUTHMGR_PORT_MAB_AUTH_TYPE_EAP_MD5
#define FD_AUTHMGR_PASS_TEXT                        " "
//#define FD_AUTHMGR_DEFAULT_EAPOL_BROAD_ACTION       BROAD_ACTION_TRAP_TO_CPU
#define FD_AUTHMGR_DEFAULT_PORT_AUTH_VIOLATION_MODE  AUTHMGR_PORT_AUTH_VIOLATION_RESTRICT
#define FD_AUTHMGR_RADIUS_MAX_AUTH_ATTEMPTS          AUTHMGR_RADIUS_MAX_AUTH_ATTEMPTS
#define FD_AUTHMGR_MONITOR_MODE                      DISABLE
#define FD_AUTHMGR_ACCT_PERIODIC_TIMEOUT            0
#define FD_AUTHMGR_ACCT_NEW_INFO                     FALSE

/* Unauthorized protocol allow defaults */
#define FD_AUTHMGR_PORT_UNAUTH_DHCP_ALLOW            FALSE
#define FD_AUTHMGR_PORT_UNAUTHPROTOALLOW_LIST       { FD_AUTHMGR_PORT_UNAUTH_DHCP_ALLOW }

#define FD_AUTHMGR_CRITICAL_RECOVERY_MAX_REAUTH  10
#define FD_AUTHMGR_PORT_CRITICAL_VLAN             0
#define FD_AUTHMGR_AUTH_EVENT_SERVER_DEAD_ACTION         AUTHMGR_AUTH_EVENT_SERVER_ACTION_NONE
#define FD_AUTHMGR_AUTH_EVENT_SERVER_ALIVE_ACTION        AUTHMGR_AUTH_EVENT_SERVER_ACTION_NONE
#define FD_AUTHMGR_AUTH_EVENT_SERVER_DEAD_VOICE_ACTION   AUTHMGR_AUTH_EVENT_SERVER_ACTION_NONE

#define FD_AUTHMGR_RATE_LIMIT       15
#define FD_AUTHMGR_BURST_INTERVAL   1

/* MAB Factory Defaults */
#define FD_MAB_MSG_COUNT                      1024
#define FD_MAB_PORT_MAB_ENABLED               DISABLE
#define FD_MAB_PORT_MAB_AUTH_TYPE             AUTHMGR_PORT_MAB_AUTH_TYPE_EAP_MD5
#define FD_MAB_PORT_SERVER_TIMEOUT            30 /* seconds */

#endif /* DEFAULTCONFIG_H */
