#!/bin/bash

### BEGIN INIT INFO
# Provides:          setup-board
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Setup Inventec d7332 board.
### END INIT INFO

case "$1" in
start)
	echo -n "Setting up board... "
	
	/usr/local/bin/inventec_d7332_util.py -f install
	echo "done."
	;;

stop)
    
        /usr/local/bin/inventec_d7332_util.py -f clean
	echo "done."

	;;

force-reload|restart)
	echo "Not supported"
	;;

*)
	echo "Usage: /etc/init.d/platform-modules-d7332.init {start|stop}"
	exit 1
	;;
esac

exit 0
