d7264/utils/inventec_d7264_util.py                      usr/local/bin
common/utils/transceiver_monitor.py                     usr/share/sonic/device/x86_64-inventec_d7264-r0/plugins
common/utils/asic_monitor.py                            usr/share/sonic/device/x86_64-inventec_d7264-r0/plugins
common/utils/platform_status.py                         usr/share/sonic/device/x86_64-inventec_d7264-r0/plugins
systemd/platform-modules-d7264.service                  lib/systemd/system
d7264/utils/sonic_platform-1.0-py2-none-any.whl         usr/share/sonic/device/x86_64-inventec_d7264-r0
