/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Chip Support
 */

/*
 * Select your target MAC chip(s)
 */
#undef  CONFIG_SDK_RTL9310
#undef  CONFIG_SDK_RTL9300
#undef  CONFIG_SDK_RTL8390
#undef  CONFIG_SDK_RTL8380

/*
 * Select your target PHYs chip
 */
#undef  CONFIG_SDK_RTL8208D
#undef  CONFIG_SDK_RTL8208G
#undef  CONFIG_SDK_RTL8208L
#undef  CONFIG_SDK_RTL8212B
#undef  CONFIG_SDK_RTL8214B
#undef  CONFIG_SDK_RTL8214FB
#define CONFIG_SDK_RTL8214FC 1
#undef  CONFIG_SDK_RTL8214C
#undef  CONFIG_SDK_RTL8214QF
#define  CONFIG_SDK_RTL8218B 1
#define CONFIG_SDK_RTL8218D 1
#define CONFIG_SDK_RTL8218E 1
#undef  CONFIG_SDK_RTL8218FB
#undef  CONFIG_SDK_RTL8226
#undef  CONFIG_SDK_RTL8295R
#undef  CONFIG_SDK_RTL826X
#undef  CONFIG_SDK_RTL826XI
#undef  CONFIG_SDK_RTL825X
#undef  CONFIG_SDK_RTL825XI
#undef  CONFIG_SDK_RTL825XL
#undef  CONFIG_SDK_RTL8224

/*
 * Select your target Peripheral chip
 */
#undef  CONFIG_SDK_RTL8231

/*
 * Select customer defined PHYs chip
 */
#undef  CONFIG_SDK_PHY_CUST1
#undef  CONFIG_SDK_PHY_CUST2
#undef  CONFIG_SDK_PHY_CUST3
#undef  CONFIG_SDK_PHY_CUST4
#undef  CONFIG_SDK_PHY_CUST5

/*
 * CPU
 */
#undef  CONFIG_SDK_EXTERNAL_CPU
#undef  CONFIG_SDK_ENDIAN_LITTLE

/*
 * Operating System
 */
#define CONFIG_SDK_KERNEL_LINUX 1
#undef  CONFIG_SDK_OS_KERNEL_OTHER
#undef  CONFIG_SDK_KERNEL_LINUX_KERNEL_MODE
#define CONFIG_SDK_KERNEL_LINUX_USER_MODE 1
#define CONFIG_SDK_KERNEL_LINUX_MODULE_LOADABLE 1

/*
 * SDK Driver
 */

/*
 * Rtcore Driver support
 */
#undef  CONFIG_SDK_DRIVER_RTCORE
#undef  CONFIG_SDK_DRIVER_RTCORE_IN_LINUX_KERNEL
#undef  CONFIG_SDK_DRIVER_NIC
#undef  CONFIG_SDK_DRIVER_EXTC_NIC
#undef  CONFIG_SDK_DRIVER_EXTC_PCI
#undef  CONFIG_SDK_DRIVER_NIC_R9310
#undef  CONFIG_SDK_DRIVER_NIC_R9300
#undef  CONFIG_SDK_DRIVER_NIC_R8390
#undef  CONFIG_SDK_DRIVER_NIC_R8380
#undef  CONFIG_SDK_DRIVER_L2NTFY_R9310
#undef  CONFIG_SDK_DRIVER_L2NTFY_R9300
#undef  CONFIG_SDK_DRIVER_L2NTFY_R8390
#undef  CONFIG_SDK_DRIVER_I2C_R9310
#undef  CONFIG_SDK_DRIVER_I2C_R9300
#undef  CONFIG_SDK_DRIVER_I2C_R8390
#undef  CONFIG_SDK_DRIVER_I2C_R8380

/*
 * Rtk Driver / RTK API support
 */
#undef  CONFIG_SDK_DRIVER_RTK
#undef  CONFIG_SDK_DRIVER_RTK_LEGACY_API
#undef  CONFIG_SDK_DRIVER_RTK
#undef  CONFIG_SDK_DRIVER_MX
#undef  CONFIG_SDK_DRIVER_COMPILE

/*
 * SDK Application
 */
#define CONFIG_SDK_APP_DIAG 1
#define CONFIG_SDK_APP_DIAG_DIR_DIAG_V2 1
#undef  CONFIG_SDK_APP_DIAG_EXT
#undef  CONFIG_SDK_SQUT_CMD_OPT
#define CONFIG_SDK_APP_COMPILE 1

/*
 * SDK Debug
 */
#undef  CONFIG_SDK_DEBUG
#undef  CONFIG_SDK_DUMP_REG_WITH_NAME
#undef  CONFIG_SDK_DUMP_TABLE_WITH_NAME

/*
 * BSP Option
 */
#undef  CONFIG_SDK_BSP_FLASH
#undef  CONFIG_SDK_BSP_MTD
#define CONFIG_SDK_SPI_DEV_NONE 1
#undef  CONFIG_SDK_SPI_DEV_1
#undef  CONFIG_SDK_SPI_DEV_2
#undef  CONFIG_SDK_SPI_DEV_3
#undef  CONFIG_SDK_SPI_DEV_4
#undef  CONFIG_SDK_SPI_DEV_5
#define CONFIG_SDK_BSP_SPI_NOR_BOOT 1
#undef  CONFIG_SDK_BSP_SPI_NAND_BOOT

/*
 * Misc Option
 */
#undef  CONFIG_SDK_FPGA_PLATFORM
#undef  CONFIG_SDK_DRIVER_TEST
#undef  CONFIG_SDK_MODEL_MODE
#undef  CONFIG_SDK_LINKED_KMOD
#undef  CONFIG_TRUNK_FAILOVER_HANDLING
#undef  CONFIG_SDK_RX_THREAD
#define CONFIG_SDK_LINKMON_POLLING_MODE 1
#undef  CONFIG_SDK_LINKMON_ISR_MODE
#undef  CONFIG_SDK_LINKMON_MIXED_MODE
#undef  CONFIG_RISE
#undef  CONFIG_SDK_HW_PROFILE_PROBE_GPIO
#define CONFIG_SDK_HW_PROFILE_PROBE_UBOOT_ENV 1
#define CONFIG_SDK_OS_VERSION "n"
#define CONFIG_SDK_COMPILER_VERSION "n"
#define CONFIG_SDK_LIBC_VERSION "n"
