schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - internal
    - internal-202012
    - internal-201911
    - internal-201811
  always: false
trigger: none
pr: none
resources:
  repositories:
  - repository: acs-buildimage
    type: git
    name: One/Networking-acs-buildimage
    ref: internal

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool: sonic-image-builder-1ES

parameters:
- name: 'jobFilters'
  type: object
  default:
  - vs
  - generic
  - barefoot
  - broadcom
  - mellanox
  - marvell-armhf
- name: 'trusty8LinkPath'
  type: string
  default: 'default'

variables:
- group: SONIC-BUILD-VG-1
- name: PUBLISH_BLOB_PREFIX
  value: pipelines/$(Build.DefinitionName)/$(Build.SourceBranchName)
- template: .azure-pipelines/template-variables.yml@acs-buildimage

stages:
- stage: Build
  variables:
    BUILD_TIMESTAMP: $[format('{0:yyyyMMdd}.{0:HHmmss}', pipeline.startTime)]
    BRANCH_NAME: $(Build.SourceBranchName)
    BUILD_NUMBER: $(Build.BuildId)
    PLATFORM_ARCH: amd64
    PASSWORD: $(SONIC_PASSWORD)
    BUILD_OPTIONS: 'SONIC_BUILD_JOBS=4 ENABLE_DHCP_GRAPH_SERVICE=y SHUTDOWN_BGP_ON_START=y ENABLE_PFCWD_ON_START=y SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/$(GROUP_NAME)'
    VERSION_PATH: target/sonic.version
    DOCKER_DATA_ROOT_FOR_MULTIARCCH: /data/march/docker
  jobs:
  - template: .azure-pipelines/azure-pipelines-job-groups.yml@acs-buildimage
    parameters:
      scriptEnv:
        PASSWORD: '$(PASSWORD)'
      jobFilters: ${{ parameters.jobFilters }}
      preSteps:
        - template: .pipelines/prepare_agent.yml@acs-buildimage
        - template: .azure-pipelines/cleanup.yml@acs-buildimage
        - checkout: self
          clean: true
          submodules: recursive
          displayName: 'Checkout code'
        - script: |
            unset REGISTRY_SERVER
            git checkout -b $(Build.SourceBranchName)
            . functions.sh
            SONIC_VERSION=$(sonic_get_version)
            echo SONIC_VERSION=${SONIC_VERSION} > sonic.properties
            LATEST_TAG=$(git describe --tags --abbrev=0)
            [[ $LATEST_TAG == *-merge ]] && LATEST_TAG=
            mkdir -p target/release
            rm -f target/sonic-installers
            echo $SONIC_VERSION > $VERSION_PATH
            echo "SONIC_VERSION=$SONIC_VERSION, LATEST_TAG=$LATEST_TAG"
            echo "##vso[task.setvariable variable=SONIC_VERSION]$SONIC_VERSION"
            echo "##vso[task.setvariable variable=LATEST_TAG]$LATEST_TAG"
            ENABLE_DOCKER_BASE_PULL=y make PLATFORM=$(GROUP_NAME) PLATFORM_ARCH=$(PLATFORM_ARCH) $(BUILD_OPTIONS) configure
          displayName: 'Make configure'
      postSteps:
        - task: ManifestGeneratorTask@0
          displayName: "Manifest Generator"
          inputs:
            BuildDropPath: $(System.DefaultWorkingDirectory)/target
        - publish: $(System.DefaultWorkingDirectory)/target
          artifact: 'sonic-buildimage.$(GROUP_NAME)'
          displayName: "Archive sonic image"
        - script: |
            touch target/sonic-installers
            for image in `ls target | grep -E "\.(swi|bin|raw|deb)$"`; do
              version_image=$(echo $image | sed -E "s/(-dbg\.\w+|\.\w+)$/-$(SONIC_VERSION)\1/")
              echo "$image,$version_image" >> target/sonic-installers
              cp -f target/$image target/$version_image
            done
          displayName: "Copy installers"
        - script: |
            export AZCOPY_LOG_LOCATION=$(pwd)/azcopy
            PUBLISH_PLATFORM_URL="https://$(SONIC_STORAGE_ACCOUNT).blob.core.windows.net/images/$(PUBLISH_BLOB_PREFIX)/$(GROUP_NAME)"
            PUBLISH_URL="$PUBLISH_PLATFORM_URL/$(Build.BuildId)$StorageSASKey"
            azcopy copy target "$PUBLISH_PLATFORM_URL/$(Build.BuildId)$StorageSASKey" --recursive=true --put-md5
            touch prev_build
            azcopy copy "$PUBLISH_PLATFORM_URL/latest_build$StorageSASKey" latest_build || true
            [ -f latest_build ] && mv latest_build prev_build
            echo $(Build.BuildId) > latest_build
            azcopy copy latest_build "$PUBLISH_PLATFORM_URL/latest_build$StorageSASKey"  --put-md5
            azcopy copy prev_build "$PUBLISH_PLATFORM_URL/prev_build$StorageSASKey"  --put-md5
          env:
            StorageSASKey: $(SONIC_STORAGE_SASKEY)
          displayName: "Publish to Azure Storage"
        - task: SSH@0
          displayName: "Make soft links for trusty8"
          inputs:
            sshEndpoint: 'acs-trusty8'
            runOptions: 'inline'
            readyTimeout: '20000'
            inline: |
              echo "Make link for $(PUBLISH_BLOB_PREFIX)"
              LINK_FOLDERNAMES=.
              [ "$(SONIC_VERSION)" == "$(LATEST_TAG)" ] && LINK_FOLDERNAMES=". tagged"
              for link_foldername in $LINK_FOLDERNAMES; do
                LATEST_VERSION=
                PREVIOUS_VERSION=
                latest_path=/azmirrors/$(PUBLISH_BLOB_PREFIX)/$(GROUP_NAME)/$(BUILD_NUMBER)
                BRANCH_NAME=$(BRANCH_NAME)
                [[ "${{ parameters.trusty8LinkPath }}" != 'default' ]] && BRANCH_NAME=${{ parameters.trusty8LinkPath }}
                link_path=/data/$(dirname $(PUBLISH_BLOB_PREFIX))/$(GROUP_NAME)/$BRANCH_NAME/$link_foldername
                [ -e $link_path/latest ] && LATEST_VERSION=$(cat $link_path/latest/target/sonic.version)
                mkdir -p $link_path

                # Make soft links for latest and prev
                prev_link_path=$(realpath $link_path/latest)
                # If the latest version in the storage account is the same as the current build version, not update the prev link
                if [ -e $prev_link_path ] && [ "$LATEST_VERSION" != "$(SONIC_VERSION)" ]; then
                  [ -L $link_path/prev ] && PREVIOUS_VERSION=$(cat $link_path/prev/target/sonic.version)
                  ln -nsf "$prev_link_path" "$link_path/prev"
                fi

                ln -nsf "$latest_path" "$link_path/latest"

                # Make soft links for installers
                installers_path=$link_path/installers
                mkdir -p $installers_path
                ln -sf $latest_path/target/sonic.version $installers_path/sonic.version
                for installer in `cat $latest_path/target/sonic-installers`; do
                  image=$(echo $installer | cut -d, -f1)
                  version_image=$(echo $installer | cut -d, -f2)
                  ln -sf $latest_path/target/$version_image $installers_path/$image
                  ln -sf $latest_path/target/$version_image $link_path/$version_image
                  ln -sf latest/target/$image $link_path/$image
                  ln -sf prev/target/$image $link_path/$image.PREV.1
                done

                # Remove the old soft links
                echo "PREVIOUS_VERSION=$PREVIOUS_VERSION"
                if [ -n "$PREVIOUS_VERSION" ]; then
                  rm -f $link_path/*"$PREVIOUS_VERSION"*
                fi
              done
        - script: |
            SONIC_VERSION=$(cat $VERSION_PATH)
            PORT=443
            DOCKERS=$(ls target/docker-*.gz)
            BRANCH=$(Build.SourceBranchName)
            for f in $DOCKERS; do
              echo $f
              ./push_docker.sh $f $REGISTRY_SERVER_INTERNAL $PORT $REGISTRY_USERNAME "$REGISTRY_PASSWD" $SONIC_VERSION $BRANCH
              ./push_docker.sh $f $REGISTRY_SERVER_INTERNAL $PORT $REGISTRY_USERNAME "$REGISTRY_PASSWD" latest $BRANCH
            done
          env:
            REGISTRY_PASSWD: $(REGISTRY_PASSWD)
            BUILD_NUMBER: $(Build.BuildId)
          displayName: "Publish to Docker Registry"
        - task: ComponentGovernanceComponentDetection@0
        - script: |
            sudo rm -rf fsroot
            docker rmi -f $(docker images docker-* -a -q | grep docker-) || true
          displayName: "CleanUp"
      jobGroups:
        - name: vs
          script: |
            OPTIONS="$BUILD_OPTIONS SONIC_DPKG_CACHE_METHOD=wcache PASSWORD=$PASSWORD"
            make $OPTIONS target/docker-sonic-vs.gz target/sonic-vs.img.gz target/docker-ptf.gz
        - name: generic
          script: |
            OPTIONS="$BUILD_OPTIONS SONIC_DPKG_CACHE_METHOD=wcache PASSWORD=$PASSWORD"
            make $OPTIONS target/sonic-generic.bin
        - name: broadcom
          script: |
            OPTIONS="$BUILD_OPTIONS SONIC_DPKG_CACHE_METHOD=wcache PASSWORD=$PASSWORD"
            echo "==== Building slim images"
            echo "INCLUDE_ACMS = n" > rules/config.user
            echo "INCLUDE_MUX = n" >> rules/config.user
            echo "INCLUDE_KUBERNETES = n" >> rules/config.user
            echo "INCLUDE_MACSEC = n" >> rules/config.user
            make $OPTIONS target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi
            mv target/sonic-broadcom.bin target/sonic-broadcom-slim.bin
            mv target/sonic-aboot-broadcom.swi target/sonic-aboot-broadcom-slim.swi
            rm rules/config.user
            echo "==== Finished building slim images"

            echo "==== Building regular images"
            make $OPTIONS target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi target/sonic-broadcom.raw
            mv target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi target/sonic-broadcom.raw target/release/
            echo "==== Finished building regular images"

            echo "==== Building syncd-rpc docker"
            make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-brcm-rpc.gz
            echo "==== Finished building syncd-rpc docker"

            echo "==== Building one debug image"
            make $OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-broadcom.bin
            mv target/sonic-broadcom.bin target/sonic-broadcom-dbg.bin
            echo "==== Finished building one debug image"

            mv target/release/* target/
        - name: mellanox
          script: |
            OPTIONS="$BUILD_OPTIONS SONIC_DPKG_CACHE_METHOD=wcache PASSWORD=$PASSWORD"
            make $OPTIONS target/sonic-mellanox.bin && make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-mlnx-rpc.gz
            cp target/debs/buster/python-saithrift_0.9.4_amd64.deb target/python-saithrift_0.9.4_amd64.deb
        - name: barefoot
          script: |
            sudo modprobe overlay
            OPTIONS="$BUILD_OPTIONS PASSWORD=$PASSWORD"
            make $OPTIONS target/sonic-barefoot.bin target/sonic-aboot-barefoot.swi && make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-bfn-rpc.gz
        - name: marvell-armhf
          pool: sonic-armhf
          timeoutInMinutes: 2160
          variables:
            PLATFORM_ARCH: armhf
          script: |
            OPTIONS="$BUILD_OPTIONS PASSWORD=$PASSWORD"
            make $OPTIONS target/sonic-marvell-armhf.bin
