#!/bin/sh

mr_reboot() {

    #echo "mr_reboot"
    sudo rmmod x86-64-cameo-esc601-32q
    sudo i2cset -y 0 0x30 0xa4 0  

}

if [ $# -eq 0 ] || [ $@ = "--halt" ] || [ $@ = "-f" ] || [ $@ = "--force" ]; then
    #echo halt
    sudo /sbin/halt
elif [ $@ = "-p" ] || [ $@ = "--reboot" ] || [ $@ = "--poweroff" ]; then
    mr_reboot
else
    echo "unsupported option"
fi

