#!/usr/bin/env python3

import os
import sys
import json
import syslog
from sonic_py_common import daemon_base

BASE_PATH = "/sys/block"
FSSTATS_PATHS = ["/host/pmon/storagemon/", "/usr/share/storagemon/"]
FSSTATS_FILE = "fsio-rw-stats.json"
STATE_DB_FIELDS = ["fs_io_reads", "fs_io_writes", "latest_fs_io_reads", "latest_fs_io_writes"]
SYSLOG_ID="fsio-rw-sync"
FSSTATS_FILE_SYNC_ERROR = 127

devices = []
json_file_dict = {}

def log_info(msg):
    syslog.openlog(SYSLOG_ID)
    syslog.syslog(syslog.LOG_INFO, msg)
    syslog.closelog()

def log_error(msg):
    syslog.openlog(SYSLOG_ID)
    syslog.syslog(syslog.LOG_ERR, msg)
    syslog.closelog()

def get_storage_disks():
    fdlist = os.listdir(BASE_PATH)
    for fd in fdlist:
        if 'boot' in fd or 'loop' in fd:
            continue
        else:
            devices.append(fd)
            json_file_dict[fd] = {}

def find_fsstats_file():
    fullpath = ""

    for path in FSSTATS_PATHS:
        if os.path.exists(os.path.join(path, FSSTATS_FILE)):
            fullpath = os.path.join(path, FSSTATS_FILE)
            break

    return fullpath

def main():

    filepath = find_fsstats_file()
    if filepath == "":
        log_error("{} not found in {} directories. Cannot sync FSIO reads and writes.".format(FSSTATS_FILE, FSSTATS_PATHS))
        sys.exit(FSSTATS_FILE_SYNC_ERROR)

    state_db = daemon_base.db_connect("STATE_DB")
    get_storage_disks()

    for device in devices:

        # Sync accumulated and latest procfs reads and writes from STATE_DB
        for field in STATE_DB_FIELDS:
            json_file_dict[device][field] = state_db.hget('STORAGE_INFO|{}'.format(device), field)

    with open(filepath, 'w+') as f:
        f.write(json.dumps(json_file_dict))

    sys.exit(0)

if __name__ == "__main__":
    main()