# acms-client package

ACMS_CLIENT_VERSION = 5.22

ACMS_CLIENT = acms-client_$(ACMS_CLIENT_VERSION)_$(CONFIGURED_ARCH).deb
$(ACMS_CLIENT)_SRC_PATH = $(SRC_PATH)/security-DsmsLinux
$(ACMS_CLIENT)_DEPENDS += $(BOND)

ifneq ($(CONFIGURED_ARCH), amd64)
SONIC_MAKE_DEBS += $(ACMS_CLIENT)
endif

export ACMS_CLIENT
