# debootstrap package

DEBOOTSTRAP_VERSION = 1.0.123
DEBOOTSTRAP_VERSION_FULL = ${DEBOOTSTRAP_VERSION}+deb11u1

export DEBOOTSTRAP_VERSION DEBOOTSTRAP_VERSION_FULL

DEBOOTSTRAP = debootstrap_$(DEBOOTSTRAP_VERSION_FULL)_all.deb
$(DEBOOTSTRAP)_SRC_PATH = $(SRC_PATH)/debootstrap
SONIC_MAKE_DEBS += $(DEBOOTSTRAP)
