# Docker image for iproute

DOCKER_IPROUTE_STEM = docker-iproute
DOCKER_IPROUTE = $(DOCKER_IPROUTE_STEM).gz
$(DOCKER_IPROUTE)_PATH = $(DOCKERS_PATH)/$(DOCKER_IPROUTE_STEM)
$(DOCKER_IPROUTE)_DEPENDS += $(IPROUTE2) $(SWSS) $(LIBHIREDIS) $(LIBHIREDIS_DEV)

$(DOCKER_IPROUTE)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BUSTER)
$(DOCKER_IPROUTE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_IPROUTE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_IPROUTE)
DOCKER_IPROUTE_DBG = $(DOCKER_IPROUTE_STEM)-$(DBG_IMAGE_MARK).gz
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_IPROUTE_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_IPROUTE_DBG)

$(DOCKER_IPROUTE)_CONTAINER_NAME = iproute
$(DOCKER_IPROUTE)_RUN_OPT += --net=host --privileged -t
$(DOCKER_IPROUTE)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_IPROUTE)_RUN_OPT += -v /host/warmboot:/var/warmboot