# Docker image for SONiC platform monitoring tools

DOCKER_PIT_STEM = docker-pit
DOCKER_PIT = $(DOCKER_PIT_STEM).gz
DOCKER_PIT_DBG = $(DOCKER_PIT_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_PIT)_PATH = $(DOCKERS_PATH)/$(DOCKER_PIT_STEM)


#$(DOCKER_PIT)_PYTHON_WHEELS += $(SONIC_PLATFORM_COMMON_PY2)
#$(DOCKER_PIT)_PYTHON_WHEELS += $(SONIC_PLATFORM_COMMON_PY3)
#$(DOCKER_PIT)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY2)
#$(DOCKER_PIT)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3)
$(DOCKER_PIT)_PYTHON_WHEELS += $(SONIC_PIT_PY2)

$(DOCKER_PIT)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS)

$(DOCKER_PIT)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

$(DOCKER_PIT)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BUSTER)

SONIC_DOCKER_IMAGES += $(DOCKER_PIT)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_PIT)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_PIT_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_PIT_DBG)

$(DOCKER_PIT)_CONTAINER_NAME = pit
$(DOCKER_PIT)_RUN_OPT += --privileged -t
$(DOCKER_PIT)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_PIT)_RUN_OPT += -v /usr/share/sonic:/usr/share/sonic:ro
$(DOCKER_PIT)_RUN_OPT += -v /usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:ro

$(DOCKER_PIT)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
