# docker image for vnetping

DOCKER_VNETPING_STEM = docker-vnet-monitor
DOCKER_VNETPING = $(DOCKER_VNETPING_STEM).gz

$(DOCKER_VNETPING)_PATH = $(DOCKERS_PATH)/$(DOCKER_VNETPING_STEM)
$(DOCKER_VNETPING)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BUSTER)

ifeq ($(INCLUDE_VNETPING), y)
SONIC_DOCKER_IMAGES += $(DOCKER_VNETPING)
SONIC_BUSTER_DOCKERS += $(DOCKER_VNETPING)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_VNETPING)
endif

$(DOCKER_VNETPING)_CONTAINER_NAME = vnetping
$(DOCKER_VNETPING)_RUN_OPT += --cap-add NET_ADMIN --privileged -t
$(DOCKER_VNETPING)_RUN_OPT += -p=1021:1021/tcp

$(DOCKER_VNETPING)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
$(DOCKER_VNETPING)_BASE_IMAGE_FILES += monit_vnetping:/etc/monit/conf.d
