# docker image for vnet monitor

DOCKER_VNET_MONITOR_STEM = docker-vnet-monitor
DOCKER_VNET_MONITOR = $(DOCKER_VNET_MONITOR_STEM).gz

$(DOCKER_VNET_MONITOR)_PATH = $(DOCKERS_PATH)/$(DOCKER_VNET_MONITOR_STEM)
$(DOCKER_VNET_MONITOR)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3) $(SWSSSDK_PY3)
$(DOCKER_VNET_MONITOR)_DEPENDS += $(LIBSWSSCOMMON) $(PYTHON_SWSSCOMMON)
$(DOCKER_VNET_MONITOR)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BUSTER)

ifeq ($(INCLUDE_VNET_MONITOR), y)
SONIC_DOCKER_IMAGES += $(DOCKER_VNET_MONITOR)
SONIC_BUSTER_DOCKERS += $(DOCKER_VNET_MONITOR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_VNET_MONITOR)
endif

$(DOCKER_VNET_MONITOR)_CONTAINER_NAME = vnet_monitor
$(DOCKER_VNET_MONITOR)_RUN_OPT += --net=host --cap-add NET_ADMIN --privileged -t
$(DOCKER_VNET_MONITOR)_RUN_OPT += -p=1021:1021/tcp

$(DOCKER_VNET_MONITOR)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
$(DOCKER_VNET_MONITOR)_BASE_IMAGE_FILES += monit_vnet_monitor:/etc/monit/conf.d

