# docker image for acms

DOCKER_ACMS_STEM = docker-acms
DOCKER_ACMS = $(DOCKER_ACMS_STEM).gz

$(DOCKER_ACMS)_PATH = $(DOCKERS_PATH)/$(DOCKER_ACMS_STEM)
$(DOCKER_ACMS)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY2) $(SWSSSDK_PY2)
$(DOCKER_ACMS)_DEPENDS += $(LIBSWSSCOMMON) $(PYTHON_SWSSCOMMON)
$(DOCKER_ACMS)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BUSTER)

ifeq ($(INCLUDE_ACMS), y)
SONIC_DOCKER_IMAGES += $(DOCKER_ACMS)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_ACMS)
endif

$(DOCKER_ACMS)_VERSION = 2.0.0
$(DOCKER_ACMS)_PACKAGE_NAME = acms

$(DOCKER_ACMS)_CONTAINER_NAME = acms
$(DOCKER_ACMS)_RUN_OPT += --privileged -t
$(DOCKER_ACMS)_RUN_OPT += -v /etc/sonic/credentials:/etc/sonic/credentials:rw
$(DOCKER_ACMS)_RUN_OPT += -v /var/opt/msft:/var/opt/msft:rw

$(DOCKER_ACMS)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
