# docker image for netconf-server

DOCKER_NETCONF_SERVER_STEM = docker-sonic-netconf-server
DOCKER_NETCONF_SERVER = $(DOCKER_NETCONF_SERVER_STEM).gz
DOCKER_NETCONF_SERVER_DBG = $(DOCKER_NETCONF_SERVER_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_NETCONF_SERVER)_PATH = $(DOCKERS_PATH)/$(DOCKER_NETCONF_SERVER_STEM)

$(DOCKER_NETCONF_SERVER)_DEPENDS += $(SONIC_MGMT_COMMON)
$(DOCKER_NETCONF_SERVER)_DEPENDS += $(SONIC_NETCONF_SERVER)
$(DOCKER_NETCONF_SERVER)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS)
$(DOCKER_NETCONF_SERVER)_DBG_DEPENDS += $(SONIC_NETCONF_SERVER_DBG)

SONIC_DOCKER_IMAGES += $(DOCKER_NETCONF_SERVER)
$(DOCKER_NETCONF_SERVER)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BUSTER)

$(DOCKER_NETCONF_SERVER)_VERSION = 1.0.0
$(DOCKER_NETCONF_SERVER)_PACKAGE_NAME = netconf-server

$(DOCKER_NETCONF_SERVER)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

ifeq ($(INCLUDE_NETCONF_SERVER), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_NETCONF_SERVER)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_NETCONF_SERVER_DBG)
ifeq ($(INCLUDE_NETCONF_SERVER), y)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_NETCONF_SERVER_DBG)
endif

$(DOCKER_NETCONF_SERVER)_CONTAINER_NAME = netconf-server
$(DOCKER_NETCONF_SERVER)_RUN_OPT += --privileged -t
$(DOCKER_NETCONF_SERVER)_RUN_OPT += -v /etc/sonic:/etc/sonic:rw
$(DOCKER_NETCONF_SERVER)_RUN_OPT += -v /etc:/host_etc:ro
$(DOCKER_NETCONF_SERVER)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw
$(DOCKER_NETCONF_SERVER)_RUN_OPT += --mount type=bind,source="/var/platform/",target="/mnt/platform/"

SONIC_BOOKWORM_DOCKERS  += $(DOCKER_NETCONF_SERVER)
SONIC_BOOKWORM_DBG_DOCKERS  += $(DOCKER_NETCONF_SERVER_DBG)
