# docker image for dummyk8s

DOCKER_DUMMYK8S_STEM = docker-dummyk8s
DOCKER_DUMMYK8S = $(DOCKER_DUMMYK8S_STEM).gz

$(DOCKER_DUMMYK8S)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_DUMMYK8S)_PATH = $(DOCKERS_PATH)/$(DOCKER_DUMMYK8S_STEM)

$(DOCKER_DUMMYK8S)_VERSION = 1.0.0
$(DOCKER_DUMMYK8S)_PACKAGE_NAME = dummyk8s

SONIC_DOCKER_IMAGES += $(DOCKER_DUMMYK8S)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_DUMMYK8S)

$(DOCKER_DUMMYK8S)_CONTAINER_NAME = dummyk8s

SONIC_BULLSEYE_DOCKERS += $(DOCKER_DUMMYK8S)
SONIC_BULLSEYE_DBG_DOCKERS += $(DOCKER_DUMMYK8S_DBG)
