DOCKER_NAMESPACE = docker-namespace.gz
DOCKER_NAMESPACE_STEM = docker-namespace
$(DOCKER_NAMESPACE)_PATH = $(DOCKERS_PATH)/$(DOCKER_NAMESPACE_STEM)

$(DOCKER_NAMESPACE)_CONTAINER_NAME = namespace

# Include in service/mgmt script generation
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_NAMESPACE)

# Include as Make target
SONIC_DOCKER_IMAGES += $(DOCKER_NAMESPACE)

SONIC_STRETCH_DOCKERS += $(DOCKER_NAMESPACE)
