# docker image for nac 

DOCKER_NAC_STEM = docker-nac
DOCKER_NAC = $(DOCKER_NAC_STEM).gz
DOCKER_NAC_DBG = $(DOCKER_NAC_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_NAC)_PATH = $(DOCKERS_PATH)/$(DOCKER_NAC_STEM)

$(DOCKER_NAC)_DEPENDS += $(SWSS) $(HOSTAPD) $(LIBSWSSCOMMON) $(LIBNL3) $(LIBNL_GENL3) $(LIBNL_ROUTE3) $(SONIC_UTILITIES_DATA)
$(DOCKER_NAC)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_NAC)_DBG_DEPENDS += $(SWSS_DBG) $(HOSTAPD_DBG) $(LIBSWSSCOMMON_DBG)

$(DOCKER_NAC)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

$(DOCKER_NAC)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_NAC)_INSTALL_PYTHON_WHEELS = $(SONIC_UTILITIES_PY3)
$(DOCKER_NAC)_INSTALL_DEBS = $(PYTHON3_SWSSCOMMON) $(LIBYANG_PY3)

SONIC_DOCKER_IMAGES += $(DOCKER_NAC)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_NAC_DBG)

ifeq ($(INCLUDE_KUBERNETES),y)
$(DOCKER_NAC)_DEFAULT_FEATURE_OWNER = kube
endif
$(DOCKER_NAC)_DEFAULT_FEATURE_STATE_ENABLED = y

ifeq ($(INCLUDE_NAC),y)
ifeq ($(INSTALL_DEBUG_TOOLS),y)
SONIC_PACKAGES_LOCAL += $(DOCKER_NAC_DBG)
SONIC_BULLSEYE_DBG_DOCKERS += $(DOCKER_NAC_DBG)
else
SONIC_PACKAGES_LOCAL += $(DOCKER_NAC)
SONIC_BULLSEYE_DOCKERS += $(DOCKER_NAC)
endif
endif

$(DOCKER_NAC)_CONTAINER_NAME = nac
$(DOCKER_NAC)_VERSION = 1.0.0
$(DOCKER_NAC)_PACKAGE_NAME = nac
$(DOCKER_NAC)_RUN_OPT += --privileged -t
$(DOCKER_NAC)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_NAC)_RUN_OPT += -v /host/warmboot:/var/warmboot

$(DOCKER_NAC)_SERVICE_REQUIRES = updategraph
$(DOCKER_NAC)_SERVICE_AFTER = swss syncd

$(DOCKER_NAC)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
