# docker image for rest-api

DOCKER_RESTAPI_TEST_STEM = docker-sonic-restapi-test
DOCKER_RESTAPI_TEST = $(DOCKER_RESTAPI_TEST_STEM).gz

$(DOCKER_RESTAPI_TEST)_DEPENDS += $(LIBHIREDIS) $(LIBNL3) $(LIBNL_GENL3) \
                             $(REDIS_TOOLS) $(REDIS_SERVER)              \
                             $(LIBNL_ROUTE3) $(LIBSWSSCOMMON) $(RESTAPI)

$(DOCKER_RESTAPI_TEST)_PATH = $(DOCKERS_PATH)/$(DOCKER_RESTAPI_TEST_STEM)

$(DOCKER_RESTAPI_TEST)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_STRETCH)

SONIC_DOCKER_IMAGES += $(DOCKER_RESTAPI_TEST)
SONIC_STRETCH_DOCKERS += $(DOCKER_RESTAPI_TEST)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_RESTAPI_TEST)

$(DOCKER_RESTAPI_TEST)_CONTAINER_NAME = rest-api-test
$(DOCKER_RESTAPI_TEST)_RUN_OPT += --cap-add NET_ADMIN --privileged -t
$(DOCKER_RESTAPI_TEST)_RUN_OPT += -v /var/run/redis/redis.sock:/var/run/redis/redis.sock
$(DOCKER_RESTAPI_TEST)_RUN_OPT += -p=8090:8090/tcp
