# docker image for TAM

DOCKER_TAM_STEM = docker-tam
DOCKER_TAM = $(DOCKER_TAM_STEM).gz
DOCKER_TAM_DBG = $(DOCKER_TAM_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_TAM)_PATH = $(DOCKERS_PATH)/$(DOCKER_TAM_STEM)

$(DOCKER_TAM)_DEPENDS += $(SONIC_TAM) $(PYTHON_SWSSCOMMON)
$(DOCKER_TAM)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS)
$(DOCKER_TAM)_DBG_DEPENDS += $(SONIC_TAM)
$(DOCKER_TAM)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_TAM)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_TAM)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_TAM_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_TAM_DBG)

$(DOCKER_TAM)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BUSTER)

$(DOCKER_TAM)_CONTAINER_NAME = tam
$(DOCKER_TAM)_RUN_OPT += --net=host --privileged -t
$(DOCKER_TAM)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_TAM)_RUN_OPT += -v /host/warmboot:/var/warmboot


