# EVENTD package
#
EVENTD_VERSION = 1.0.0
export EVENTD_VERSION

EVENTD = eventd_$(EVENTD_VERSION)_amd64.deb
$(EVENTD)_SRC_PATH = $(SRC_PATH)/sonic-eventd
$(EVENTD)_DEPENDS += $(LIBSWSSCOMMON_DEV) $(LIBEVENTNOTIFY_DEV)
$(EVENTD)_RDEPENDS += $(LIBSWSSCOMMON) $(LIBEVENTNOTIFY)
SONIC_DPKG_DEBS += $(EVENTD)

EVENTD_DBG = eventd-dbg_1.0.0_amd64.deb
$(EVENTD_DBG)_DEPENDS += $(EVENTD)
$(EVENTD_DBG)_RDEPENDS += $(EVENTD)
$(eval $(call add_derived_package,$(EVENTD),$(EVENTD_DBG)))

export EVENTD

