# genl-packet kernel module

GENL_PACKET_VERSION_BASE = 0.0.1
GENL_PACKET_VERSION = $(GENL_PACKET_VERSION_BASE)-1

GENL_PACKET_DEV = genl-packet-dev_$(GENL_PACKET_VERSION)_$(CONFIGURED_ARCH).deb
$(GENL_PACKET_DEV)_SRC_PATH = $(SRC_PATH)/genl-packet
$(GENL_PACKET_DEV)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(GENL_PACKET_DEV)

GENL_PACKET = genl-packet_$(GENL_PACKET_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(GENL_PACKET_DEV),$(GENL_PACKET)))
