# SONiC gnmi package

SONIC_GNMI = sonic-gnmi_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_GNMI)_SRC_PATH = $(SRC_PATH)/sonic-gnmi
$(SONIC_GNMI)_DEPENDS  = $(SONIC_MGMT_COMMON) $(SONIC_MGMT_COMMON_CODEGEN) \
                            $(LIBHIREDIS_DEV) $(LIBNL3_DEV) $(LIBNL_GENL3_DEV) \
                            $(LIBNL_ROUTE3_DEV) $(LIBSWSSCOMMON_DEV) $(LIBSWSSCOMMON)
$(SONIC_GNMI)_RDEPENDS = $(LIBHIREDIS) $(LIBNL3) $(LIBNL_GENL3) \
                            $(LIBNL_ROUTE3) $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_GNMI)
