# SONiC gnmi package

SONIC_GNMI = sonic-gnmi_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_GNMI)_SRC_PATH = $(SRC_PATH)/sonic-gnmi
$(SONIC_GNMI)_DEPENDS  = $(SONIC_MGMT_COMMON) $(SONIC_MGMT_COMMON_CODEGEN)
$(SONIC_GNMI)_RDEPENDS = 
SONIC_DPKG_DEBS += $(SONIC_GNMI)
