# Grub2 package

GRUB2_VERSION = 2.06
GRUB2_FULL_VERSION = $(GRUB2_VERSION)-3~deb11u1

export GRUB2_VERSION
export GRUB2_FULL_VERSION

GRUB2 = grub-efi-$(CONFIGURED_ARCH)-bin_$(GRUB2_FULL_VERSION)_$(CONFIGURED_ARCH).deb
$(GRUB2)_SRC_PATH = $(SRC_PATH)/grub2
SONIC_MAKE_DEBS += $(GRUB2)
