# libhiredis package

HIREDIS_VERSION = 1.2.0
HIREDIS_VERSION_FULL = ${HIREDIS_VERSION}-4

export HIREDIS_VERSION HIREDIS_VERSION_FULL

LIBHIREDIS = libhiredis1.1.0_$(HIREDIS_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(LIBHIREDIS)_SRC_PATH = $(SRC_PATH)/hiredis
SONIC_MAKE_DEBS += $(LIBHIREDIS)

LIBHIREDIS_DEV = libhiredis-dev_$(HIREDIS_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBHIREDIS),$(LIBHIREDIS_DEV)))

LIBHIREDIS_DBG = libhiredis1.1.0-dbgsym_$(HIREDIS_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBHIREDIS),$(LIBHIREDIS_DBG)))

export LIBHIREDIS LIBHIREDIS_DEV LIBHIREDIS_DBG