# ifupdown2 package

IFUPDOWN2_VERSION = 3.0.0
IFUPDOWN2_VERSION_FULL = ${IFUPDOWN2_VERSION}-1
export IFUPDOWN2_VERSION IFUPDOWN2_VERSION_FULL

IFUPDOWN2 = ifupdown2_$(IFUPDOWN2_VERSION_FULL)_all.deb
$(IFUPDOWN2)_SRC_PATH = $(SRC_PATH)/ifupdown2
SONIC_MAKE_DEBS += $(IFUPDOWN2)

export IFUPDOWN2
