# iproute2 package

IPROUTE2_VERSION = 4.9.0-1

IPROUTE2 = iproute2_$(IPROUTE2_VERSION)_$(CONFIGURED_ARCH).deb
$(IPROUTE2)_SRC_PATH = $(SRC_PATH)/iproute2
$(IPROUTE2)_DEPENDS += $(LIBHIREDIS) $(LIBHIREDIS_DEV)
SONIC_MAKE_DEBS += $(IPROUTE2)

IPROUTE2_DBG = iproute2-dbgsym_$(IPROUTE2_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(IPROUTE2),$(IPROUTE2_DBG)))

export IPROUTE2
export IPROUTE2_DBG
