# SONiC event notfiy library

LIBEVENTNOTIFY_VERSION = 1.0.0
LIBEVENTNOTIFY = libeventnotify_$(LIBEVENTNOTIFY_VERSION)_amd64.deb
$(LIBEVENTNOTIFY)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(LIBEVENTNOTIFY)_RDEPENDS += $(LIBSWSSCOMMON)

$(LIBEVENTNOTIFY)_SRC_PATH = $(SRC_PATH)/sonic-eventd/lib
SONIC_DPKG_DEBS += $(LIBEVENTNOTIFY)

LIBEVENTNOTIFY_DEV = libeventnotify-dev_$(LIBEVENTNOTIFY_VERSION)_amd64.deb
$(eval $(call add_derived_package,$(LIBEVENTNOTIFY),$(LIBEVENTNOTIFY_DEV)))

