# libndp-tools package, in bookworm this can probably be removed
# Force debian 12 package as debian 11 doesn't support 
# required libndp-tools version.

LIBNDP_TOOLS_VERSION = 1.8
LIBNDP0_VERSION = ${LIBNDP_TOOLS_VERSION}
LIBNDP_TOOLS_VERSION_FULL = ${LIBNDP_TOOLS_VERSION}-1+deb12u1
LIBNDP0_VERSION_FULL = ${LIBNDP_TOOLS_VERSION_FULL}

export LIBNDP_TOOLS_VERSION LIBNDP_TOOLS_VERSION_FULL
export LIBNDP0_VERSION LIBNDP0_VERSION_FULL

LIBNDP0 = libndp0_$(LIBNDP_TOOLS_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(LIBNDP0)_SRC_PATH = $(SRC_PATH)/ndptool

LIBNDP_TOOLS = libndp-tools_$(LIBNDP_TOOLS_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(LIBNDP_TOOLS)_SRC_PATH = $(SRC_PATH)/ndptool

$(LIBNDP_TOOLS)_DEPENDS += \
    $(LIBNDP0)
$(LIBNDP_TOOLS)_RDEPENDS  += \
    $(LIBNDP0)
SONIC_MAKE_DEBS += $(LIBNDP_TOOLS) $(LIBNDP0)

export LIBNDP0 LIBNDP_TOOLS