# lm-senensors package

LM_SENSORS_VERSION=3.4.0
LM_SENSORS_VERSION_FULL=$(LM_SENSORS_VERSION)-4

LM_SENSORS = lm-sensors_$(LM_SENSORS_VERSION_FULL)_amd64.deb
$(LM_SENSORS)_SRC_PATH = $(SRC_PATH)/lm-sensors


SONIC_MAKE_DEBS += $(LM_SENSORS)

export LM_SENSORS
export LM_SENSORS_VERSION 
export LM_SENSORS_VERSION_FULL
