# SONiC PAC package

PAC_VERSION = 1.0.0
export PAC_VERSION

SONIC_PAC = pac_$(PAC_VERSION)_amd64.deb
$(SONIC_PAC)_SRC_PATH = $(SRC_PATH)/sonic-pac
$(SONIC_PAC)_DEPENDS = $(LIBSWSSCOMMON_DEV) $(HOSTAPD) $(LIBHOSTCOMM_DEV)
$(SONIC_PAC)_RDEPENDS = $(LIBSWSSCOMMON) $(HOSTAPD) $(LIBHOSTCOMM)
SONIC_DPKG_DEBS += $(SONIC_PAC)

SONIC_PAC_DBG = pac-dbg_1.0.0_amd64.deb
$(SONIC_PAC_DBG)_DEPENDS += $(SONIC_PAC)
$(SONIC_PAC_DBG)_RDEPENDS += $(SONIC_PAC)
$(eval $(call add_derived_package,$(SONIC_PAC),$(SONIC_PAC_DBG)))

