# radvd package

RADVD_VERSION = 2.17-2~bpo9+1

export RADVD_VERSION

RADVD = radvd_$(RADVD_VERSION)_$(CONFIGURED_ARCH).deb
$(RADVD)_SRC_PATH = $(SRC_PATH)/radvd
SONIC_MAKE_DEBS += $(RADVD)
SONIC_STRETCH_DEBS += $(RADVD)
