# saiserver

SAISERVER = saiserver
$(SAISERVER)_DEPENDS += $(THRIFT_COMPILER) $(LIBTHRIFT_DEV)
$(SAISERVER)_RDEPENDS += $(LIBTHRIFT)
$(SAISERVER)_SRC_PATH = $(SRC_PATH)/saiserver
SONIC_MAKE_DEBS += $(SAISERVER)
