# Shim package

SHIM_VERSION = 15.6
SHIM_FULL_VERSION = $(SHIM_VERSION)-1~deb11u1

export SHIM_VERSION
export SHIM_FULL_VERSION

SHIM = shim-unsigned_$(SHIM_FULL_VERSION)_$(CONFIGURED_ARCH).deb
$(SHIM)_SRC_PATH = $(SRC_PATH)/shim
SONIC_MAKE_DEBS += $(SHIM)
