# socat packages

SOCAT_VERSION = 1.7.4.1
SOCAT_VERSION_FULL = ${SOCAT_VERSION}-3

export SOCAT_VERSION
export SOCAT_VERSION_FULL

SOCAT = socat_$(SOCAT_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(SOCAT)_SRC_PATH = $(SRC_PATH)/socat
SONIC_MAKE_DEBS += $(SOCAT)
