# sonic-device-data Debian package

SONIC_DEVICE_DATA_VERSION = 1.0

export SONIC_DEVICE_DATA_VERSION

SONIC_DEVICE_DATA = sonic-device-data_$(SONIC_DEVICE_DATA_VERSION)_all.deb
$(SONIC_DEVICE_DATA)_SRC_PATH = $(SRC_PATH)/sonic-device-data
SONIC_MAKE_DEBS += $(SONIC_DEVICE_DATA)
