# SONIC_STP package
#
STP_VERSION = 1.0.0
export STP_VERSION

SONIC_STP = stp_$(STP_VERSION)_amd64.deb
$(SONIC_STP)_SRC_PATH = $(SRC_PATH)/sonic-stp
$(SONIC_STP)_DEPENDS += $(LIBEVENT)
$(SONIC_STP)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(SONIC_STP)_RDEPENDS += $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_STP)

SONIC_STP_DBG = stp-dbg_1.0.0_amd64.deb
$(SONIC_STP_DBG)_DEPENDS += $(SONIC_STP)
$(SONIC_STP_DBG)_RDEPENDS += $(SONIC_STP)
$(eval $(call add_derived_package,$(SONIC_STP),$(SONIC_STP_DBG)))

export SONIC_STP
