# SONiC telemetry package

SONIC_TELEMETRY = sonic-telemetry_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_TELEMETRY)_SRC_PATH = $(SRC_PATH)/sonic-telemetry
$(SONIC_TELEMETRY)_DEPENDS  = $(SONIC_MGMT_COMMON) $(SONIC_MGMT_COMMON_CODEGEN) \
    $(LIBSAIREDIS_DEV) $(LIBSAIMETADATA_DEV) $(LIBSWSSCOMMON_DEV) $(LIBSWSSCOMMON) 
$(SONIC_TELEMETRY)_RDEPENDS = $(LIBSAIREDIS) $(LIBSAIMETADATA) \
    $(LIBSWSSCOMMON) $(LIBSWSSCOMMON_DEV)
SONIC_DPKG_DEBS += $(SONIC_TELEMETRY)
