# docker image for docker-ptf

DOCKER_PTF_PY3 = docker-ptf-py3.gz
$(DOCKER_PTF_PY3)_PYTHON_WHEELS += $(PTF_PY3)
$(DOCKER_PTF_PY3)_PATH = $(DOCKERS_PATH)/docker-ptf-py3
$(DOCKER_PTF_PY3)_DEPENDS += $(LIBTHRIFT_0_14_1) $(PYTHON3_THRIFT_0_14_1) $(PYTHON_SAITHRIFT)
SONIC_DOCKER_IMAGES += $(DOCKER_PTF_PY3)
SONIC_BUSTER_DOCKERS += $(DOCKER_PTF_PY3)
