#!/usr/bin/python
import json
import os

database_config_file = "/etc/sonic/database_config.json"

data = {}
if os.path.isfile(database_config_file):
    with open(database_config_file, "r") as read_file:
        data = json.load(read_file)

if 'DATABASE' in data:
    for inst in data["DATABASE"]:
        port = data["DATABASE"][inst]["port"]
        os.system("create_single_redis_config.sh " + inst + " " + str(port))
