{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-stretch

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Update apt's cache of available packages
RUN apt-get update

{% if docker_database_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_database_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_database_debs.split(' ')) }}
{%- endif %}

# Clean up
RUN apt-get clean -y                                  && \
    apt-get autoclean -y                              && \
    apt-get autoremove -y                             && \
    rm -rf /debs ~/.cache                             && \
    sed -ri 's/^(save .*$)/# \1/g;                       \
             s/^daemonize yes$/daemonize no/;            \
             s/^logfile .*$/logfile ""/;                 \
             s/^# syslog-enabled no$/syslog-enabled no/; \
             s/^# unixsocket/unixsocket/;                \
             s/redis-server.sock/redis.sock/g;           \
             s%pidfile .*%pidfile /var/run/redis/redis.pid%; \
             s/^client-output-buffer-limit pubsub [0-9]+mb [0-9]+mb [0-9]+/client-output-buffer-limit pubsub 0 0 0/ \
            ' /etc/redis/redis.conf

RUN sed -ri 's%DAEMON_ARGS=.*%DAEMON_ARGS=/etc/`basename ${0}`/`basename ${0}`.conf%;  \
             s/NAME=.*/NAME=`basename ${0}`/;                                          \
             s/DESC=.*/DESC=`basename ${0}`/;                                          \
             s%RUNDIR=.*%RUNDIR=/var/run/`basename ${0}`%;                             \
             s%PIDFILE=.*%PIDFILE=$RUNDIR/`basename ${0}`.pid%;                        \
             ' /etc/init.d/redis-server

RUN cp /etc/init.d/redis-server /etc/init.d/redis
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["create_single_redis_config.sh", "/usr/local/bin/"]
COPY ["create_all_redis_config", "/usr/local/bin/"]
COPY ["start_single_redis_server.sh", "/usr/local/bin/"]
COPY ["start_all_redis_servers", "/usr/local/bin/"]

ENTRYPOINT ["/usr/bin/supervisord"]
