#!/usr/bin/python
from swsscommon.swsscommon import SonicDBConfig
import redis
import subprocess
import time

while(True):
    output = subprocess.Popen(['sonic-db-cli', 'PING'], stdout=subprocess.PIPE).communicate()[0]
    if 'PONG' in output:
        break
    time.sleep(1)

instlists = SonicDBConfig.getInstanceList()
for instname, v in instlists.items():
    insthost = v['hostname']
    instsocket = v['unix_socket_path']

    dblists = SonicDBConfig.getDbList()
    for dbname in dblists:
        dbid = SonicDBConfig.getDbId(dbname)
        dbinst = SonicDBConfig.getDbInst(dbname)

        # this DB is on current instance, skip flush
        if dbinst == instname:
            continue

        r = redis.Redis(host=insthost, unix_socket_path=instsocket, db=dbid)
        r.flushdb()
