#!/usr/bin/python
import json
import os
import subprocess
import time

def ping_redis(cmd):
    while True:
        output = '0'
        try:
            output = subprocess.check_output(cmd, shell=True)
        except subprocess.CalledProcessError as e:
            print ("ping redis failed")

        if output != '0':
            break
        time.sleep(1)

database_config_file = "/var/run/redis/sonic-db/database_config.json"

data = {}
if os.path.isfile(database_config_file):
    with open(database_config_file, "r") as read_file:
        data = json.load(read_file)

if 'INSTANCES' in data:
    for inst in data["INSTANCES"]:
        port = data["INSTANCES"][inst]["port"]
        cmd = "redis-cli -p " + str(port) + " ping | grep -c PONG"
        ping_redis(cmd)
