# docker image for linux sonic docker image

$(LIBSAIREDIS)_DPKG_TARGET = binary-syncd-vs

DOCKER_SONIC_LINUX = docker-sonic-linux.gz
$(DOCKER_SONIC_LINUX)_PATH = $(PLATFORM_PATH)/docker-sonic-linux
$(DOCKER_SONIC_LINUX)_DEPENDS += $(SWSS) $(SYNCD_VS) $(REDIS_SERVER) $(REDIS_TOOLS) $(LIBTEAMDCT) $(LIBTEAM_UTILS) 

ifeq ($(ROUTING_STACK), quagga)
$(DOCKER_SONIC_LINUX)_DEPENDS += $(QUAGGA)
else ifeq ($(ROUTING_STACK), frr)
$(DOCKER_SONIC_LINUX)_DEPENDS += $(FRR)
else
$(DOCKER_SONIC_LINUX)_DEPENDS += $(GOBGP)
endif

$(DOCKER_SONIC_LINUX)_LOAD_DOCKERS += $(DOCKER_BASE)
SONIC_DOCKER_IMAGES += $(DOCKER_SONIC_LINUX)
