
config_data_ly1200 = {
    'board_type_path': '/sys/bus/i2c/devices/1-0032/brd_type',
    'psu_type1':  ['SE047-180G', 'SE048-180G', 'SE050-180G', 'SE049-180G'],
    'psu_type': ['FSE047-180G','FSE048-180G','FSE050-180G','FSE049-180G'],

    'mon_fan': {
        'devs': [
        {
            'cpld_path': '/sys/bus/i2c/devices/1-0032',
            'fan_fault': ['fan1_fault', 'fan2_fault'],
            'fan_fault_mask': [ 'fan1_fault_mask', 'fan2_fault_mask'],
            'fan_input': ['fan1_input', 'fan2_input'],
            'fan_panel_led': 'fan_led',
            'fan_target': [ 'fan1_target', 'fan2_target'],
            "hwmon_path": "/sys/bus/i2c/devices/3-0020/hwmon",
            'intr_msk': 'fan_alert_int_msk',
            'intr_src': 'fan_alert_int',
            'name': 'Fan1',
            'present': 'fan_tray1_present',
            'pwm': ['pwm1', 'pwm2'],
            'pwm_enable': [ 'pwm1_enable', 'pwm2_enable'],
            'tray_led': 'fan_tray1_led',
            'type': 'fan_type1',
        },
        {
            'cpld_path': '/sys/bus/i2c/devices/1-0032',
            'fan_fault': ['fan3_fault', 'fan4_fault'],
            'fan_fault_mask': [ 'fan3_fault_mask','fan4_fault_mask'],
            'fan_input': ['fan3_input', 'fan4_input'],
            'fan_panel_led': 'fan_led',
            'fan_target': [ 'fan3_target','fan4_target'],
            "hwmon_path": "/sys/bus/i2c/devices/3-0020/hwmon",
            'intr_msk': 'fan_alert_int_msk',
            'intr_src': 'fan_alert_int',
            'name': 'Fan2',
            'present': 'fan_tray2_present',
            'pwm': ['pwm3', 'pwm4'],
            'pwm_enable': [ 'pwm3_enable','pwm4_enable'],
            'tray_led': 'fan_tray2_led',
            'type': 'fan_type2'},
        {
            'cpld_path': '/sys/bus/i2c/devices/1-0032',
            'fan_fault': ['fan5_fault', 'fan6_fault'],
            'fan_fault_mask': [ 'fan5_fault_mask','fan6_fault_mask'],
            'fan_input': ['fan5_input', 'fan6_input'],
            'fan_panel_led': 'fan_led',
            'fan_target': [ 'fan5_target','fan6_target'],
            "hwmon_path": "/sys/bus/i2c/devices/3-0020/hwmon",
            'intr_msk': 'fan_alert_int_msk',
            'intr_src': 'fan_alert_int',
            'name': 'Fan3',
            'present': 'fan_tray3_present',
            'pwm': ['pwm5', 'pwm6'],
            'pwm_enable': [ 'pwm5_enable','pwm6_enable'],
            'tray_led': 'fan_tray3_led',
            'type': 'fan_type3'
        },
        {
            'cpld_path': '/sys/bus/i2c/devices/1-0032',
            'fan_fault': ['fan1_fault', 'fan2_fault'],
            'fan_fault_mask': [ 'fan1_fault_mask','fan2_fault_mask'],
            'fan_input': ['fan1_input', 'fan2_input'],
            'fan_target': [ 'fan1_target','fan2_target'],
            "hwmon_path": "/sys/bus/i2c/devices/3-0023/hwmon",
            'intr_msk': 'fan_alert_int_msk',
            'intr_src': 'fan_alert_int',
            'name': 'Fan4',
            'present': 'fan_tray4_present',
            'pwm': ['pwm1', 'pwm2'],
            'pwm_enable': [ 'pwm1_enable','pwm2_enable'],
            'tray_led': 'fan_tray4_led',
            'type': 'fan_type4'},
        { 'cpld_path': '/sys/bus/i2c/devices/1-0032',
            'fan_fault': ['fan3_fault', 'fan4_fault'],
            'fan_fault_mask': [ 'fan3_fault_mask','fan4_fault_mask'],
            'fan_input': ['fan3_input', 'fan4_input'],
            'fan_target': [ 'fan3_target','fan4_target'],
            "hwmon_path": "/sys/bus/i2c/devices/3-0023/hwmon",
            'intr_msk': 'fan_alert_int_msk',
            'intr_src': 'fan_alert_int',
            'name': 'Fan5',
            'present': 'fan_tray5_present',
            'pwm': ['pwm3', 'pwm4'],
            'pwm_enable': [ 'pwm3_enable','pwm4_enable'],
            'tray_led': 'fan_tray5_led',
            'type': 'fan_type5'},
        { 'cpld_path': '/sys/bus/i2c/devices/1-0032',
            'fan_fault': ['fan5_fault', 'fan6_fault'],
            'fan_fault_mask': [ 'fan5_fault_mask','fan6_fault_mask'],
            'fan_input': ['fan5_input', 'fan6_input'],
            'fan_target': [ 'fan5_target','fan6_target'],
            "hwmon_path": "/sys/bus/i2c/devices/3-0023/hwmon",
            'intr_msk': 'fan_alert_int_msk',
            'intr_src': 'fan_alert_int',
            'name': 'Fan6',
            'present': 'fan_tray6_present',
            'pwm': ['pwm5', 'pwm6'],
            'pwm_enable': [ 'pwm5_enable','pwm6_enable'],
            'tray_led': 'fan_tray6_led',
            'type': 'fan_type6'
        }],
        'start_smart_fan': '/etc/init.d/fan-ctrld start',
        'stop_smart_fan': '/etc/init.d/fan-ctrld stop',
        'timeout': 1000 },
    'mon_misc': {
        'devs': [
            {
                'cpld_path': '/sys/bus/i2c/devices/1-0031',
                'intr_msk': 'vrhot_irq_en',
                'intr_src': 'vrhot_irq',
                'name': 'vrhot'},
            { 'cpld_path': '/sys/bus/i2c/devices/1-0031',
                'intr_msk': 'cpu_thermtrip_irq_en',
                'intr_src': 'cpu_thermtrip_irq',
                'name': 'cpu_temp'},
            { 'cpld_path': '/sys/bus/i2c/devices/1-0031',
                'intr_msk': 'temp_alert_irq_en',
                'intr_src': 'temp_alert_irq',
                'name': 'sys_temp'},
            { 'cpld_path': '/sys/bus/i2c/devices/1-0032',
                'intr_msk': 'usb_fault_msk',
                'intr_src': 'usb_fault',
                'name': 'usb'},
            { 'cpld_path': '/sys/bus/i2c/devices/1-0032',
                'intr_msk': 'pcie_int_msk',
                'intr_src': 'pcie_int',
                'name': 'pcie'}
        ],
        #'timeout_': 1000,
    },
    'mon_psu': { 
        'devs': [
            {
                'cpld_path': '/sys/bus/i2c/devices/1-0032',
                'hwmon_path': '/sys/bus/i2c/devices/5-0058/hwmon',
                'intr_msk': 'ps1_int_msk',
                'intr_src': 'ps1_int',
                'model_reg': 'mfr_model',
                'name': 'Psu1',
                'pg_off': 6,
                'pg_ps_reg': 'psu_en_status_fld',
                'power_fault': 'ps1_pf',
                'power_good': 'ps1_pg',
                'present': 'ps1_ps',
                'ps_off': 7,
                'psu_intr_src': [ 'vout_ov_fault',
                                'vout_uv_fault',
                                'curr2_crit_alarm',
                                'curr2_max_alarm',
                                'ot_fault',
                                'ot_warning',
                                'vin_uv_warning',
                                'vin_uv_fault',
                                'fan1_fault',
                                'fan1_alarm'],
                'psu_panel_led': 'power_led',
                'sysfs_cmd': "echo 'fse000 0x58' > /sys/bus/i2c/devices/i2c-5/new_device"},
            {
                'cpld_path': '/sys/bus/i2c/devices/1-0032',
                'hwmon_path': '/sys/bus/i2c/devices/5-0059/hwmon',
                'intr_msk': 'ps2_int_msk',
                'intr_src': 'ps2_int',
                'model_reg': 'mfr_model',
                'name': 'Psu2',
                'pg_off': 2,
                'pg_ps_reg': 'psu_en_status_fld',
                'power_fault': 'ps2_pf',
                'power_good': 'ps2_pg',
                'present': 'ps2_ps',
                'ps_off': 3,
                'psu_intr_src': [ 'vout_ov_fault',
                                'vout_uv_fault',
                                'curr2_crit_alarm',
                                'curr2_max_alarm',
                                'ot_fault',
                                'ot_warning',
                                'vin_uv_warning',
                                'vin_uv_fault',
                                'fan1_fault',
                                'fan1_alarm'],
        'sysfs_cmd': "echo 'fse000 0x59' > /sys/bus/i2c/devices/i2c-5/new_device"}],
        'timeout': 1000},
}

